### ISSUE TITLE
Check for dust is incorrect, if the receiving address has an dust allowance

### ISSUE THREAD

**Issue by obany** [iotaledger/firefly#633] opened 2021-03-22 18:13 UTC
## Issue description

The check for sending dust just verifies if amount is < 1000000i, it is possible to send a value less than that amount if a destination address has a dust allowance.

## Wallet version

0.3.0

## System specification

Windows

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Try to send an amount < 1000000 to an address with dust allowance
2.
3.

## Expected behaviour

Fails with error message "You cannot send less than 1 Mi."

## Actual behaviour

Should be able to send dust to an address with dust allowance

**Comment by antalm** [comment] 2021-04-30 17:42
I think the expected behavior and the actual behavior are mixed up.
Currently one can’t send to an address already having more than 1 Mi, but the expected behavior is that one can send.

**Comment by github-i286** [comment] 2021-05-03 05:35
> I think the expected behavior and the actual behavior are mixed up.
> Currently one can’t send < 1Mi to an address already having more than 1 Mi, but the expected behavior is that one can send.

The dust protection does not allow single UTXO < 1Mi, independent on what Mi's on the address already are.
The dust protection only allows UTXOs <1Mi to an address that has a **_special crafted_** "dust allowance" UTXO between 1 Mi and 10 Mi's (1 Mi allows up to 10 dust transactions, 10 Mi allows up to 100 dust transactions).
The resolution need to be:
- allow send transactions <1Mi to addresses that have this special crafted "dust allowance" UTXO (and not already used up allowed dust transactions).
- allow creation of dust allowed addresses with a deposit of 1 to 10 Mi's. Have a special list of such dust allowed addresses to copy / QR code these. Have a special function to collect dust transaction to a "collect address" (to allow more new dust transactions to the dust address).

**Comment by Tuditi** [comment] 2022-08-02 15:12
I'm closing this down, since the issue is fixed.

**Closed by Tuditi** 2022-08-02 15:12 UTC
Labels: type:enhancement
