### ISSUE TITLE
unable to move tokens from trinity wallet to Firefly wallet

### ISSUE THREAD

**Issue by covkid** [iotaledger/firefly#1183] opened 2021-06-01 18:18 UTC
used ledger nano s on Trinity wallet with Trinity wallet so didnt get a passphase or any key so how do i move tokens to firefly? Don't see any option to import from ledger to firefly, can find nothing to find out how to do this. Cannot send from Trinity wallet to exchange or anything -totally lost on this.

Briefly describe the issue.

## Wallet version firefly version 1.1.0 

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by shufps** [comment] 2021-06-02 11:05
It's not a bug you are describing. Firefly doesn't yet support the Ledger Nano S. Please be patient - Ledger Nano S/X support is currently being worked on by the Firefly team.

**Comment by DocBrown101** [comment] 2021-06-03 13:52
Is there already a branch for this?

**Comment by vondolce** [comment] 2021-06-05 05:18
Please help, This needs to happen sooner than later, as we can not access our tokens, do trades, sell or buy at all, Trinity wallet will not let me in at all.

**Comment by juanitom9** [comment] 2021-06-07 12:32
I can't pass them to firefly either, also I don't have the seedvault downloaded and trinity doesn't work anymore, it only works for those who had it installed and configured on mobile, but not for those who had it installed and configured on PC like me, and who knows install now again on mobile does not work, so how can I download my seedvault if the application does not work for who installs it again? I have a lot of money in my wallet and I need a solution, I find it a shame that trinity is not supported for new installations and only for those who already had it downloaded.

**Comment by jeffinafix** [comment] 2021-06-21 20:02
I have Trinity installed on a desktop PC, connected to Ledger Nano S.
I can open it but can't send tokens anywhere.
I am having to dispose of this PC (can't take it with me when travelling), and have got a laptop to replace it.
Can someone please assure me that I won't lose my tokens when I no longer have access to the old PC??
Have the development team got this covered?

**Comment by wonkytonky2** [comment] 2021-06-21 20:41
> I have Trinity installed on a desktop PC, connected to Ledger Nano S.
> I can open it but can't send tokens anywhere.
> I am having to dispose of this PC (can't take it with me when travelling), and have got a laptop to replace it.
> Can someone please assure me that I won't lose my tokens when I no longer have access to the old PC??
> Have the development team got this covered?

install trinity on new pc .; see if it works there..  and you can see your coins then it's ok to get rid of old pc. 

the seed is stored on ledger, not on pc. be sure to have backup 24 words on ledger. too.

**Comment by dftrader** [comment] 2021-06-23 11:40
I am having the same issue.
The Trinity wallet will not sync with Ledger, so unable to view wallet or migrate.

Please advise soonest

**Comment by cgpro** [comment] 2021-06-30 18:52
Any news on this topic or a timeline? (Q3, Q4?)

**Comment by MotorsportGmbH** [comment] 2021-07-07 08:24
They startet community testing three days ago, to find the last bugs before releasing Ledger Support. 
App for Ledger is already available.  

I assume it will take a few days until we finally can migrate our funds

**Comment by chrisella** [comment] 2021-07-28 11:50
Anyone have any updates on this? feels like I've been waiting ages just to get this migration complete

**Comment by MotorsportGmbH** [comment] 2021-07-29 13:25
Yes, they started final testing yesterday and community ETA is 1-3 days if
nothing goes wrong.


Chris Ella ***@***.***> schrieb am Mi., 28. Juli 2021, 13:50:

**Comment by MiKeF05** [comment] 2021-08-10 19:41
Issue can be closed as it pointed to the missing support of the ledger migration.

**Comment by begonaalvarezd** [comment] 2021-08-11 08:19
Firefly with Ledger support has been released and can be downloaded at https://firefly.iota.org/

**Closed by begonaalvarezd** 2021-08-11 08:19 UTC
Labels: bug
