### ISSUE TITLE
[Bug report]: FF AppImage instantly crashes on Linux (Pop!OS 22.04)

### ISSUE THREAD

**Issue by erzwo31** [iotaledger/firefly#4261] opened 2022-08-18 12:25 UTC
### Platform

Desktop

### Version

1.6.2, 1.6.5

### Description

Maybe dublicate of: [https://github.com/iotaledger/firefly/issues/3783](url)

Today I wanted to open Firefly again (last time I used Pop!OS 21.10) and out of no reason it does not start anymore. An empty window pops up for under a second and then disappears.

What I tryed:
I have deleted the $home/.config/Firefly folder, but that does not help. This occurs on 1.6.2 and 1.6.5

$home/.config/Firefly/logs/main.log [1.6.5]
```
[2022-08-17 12:55:12.271] [info] Checking for update
[2022-08-17 12:55:12.353] [info] Generated new staging user ID: xxxxxxx 
[2022-08-17 12:55:12.460] [info] Update for version 1.6.5 is not available (latest version: 1.6.5, downgrade is disallowed).
```

$home/.config/Firefly/logs/main.log [1.6.2]
```
[2022-08-17 12:59:17.071] [info] Checking for update
[2022-08-17 12:59:17.155] [info] Generated new staging user ID: xxxxxx
[2022-08-17 12:59:17.243] [info] Found version 1.6.5 (url: firefly-desktop-1.6.5.AppImage)
```

I got the hint to disable sandbox by using the argument "--no-sandbox", which does fix my issue. So when I start FF through console with this argument, FF opens as expected. As I use the usual behaviour by double clicking the AppImage file, the explained issue comes up.

### Expected behaviour

Double clicking the AppImage file and Firefly opening normal.

### Actual behaviour

Firefly opens an empty window for under a second and crashes.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Starting the AppImage file.

### Operating System

Linux

### Diagnostics

```shell
Version 1.6.5
Language: en
Currency: USD
Node selection: Automatic
Platform: linux
Platform Version: 5.18.10-76051810-generic
Platform Architecture: x64
CPU Count: 8
Total Memory: 64217.3 MB
Free Memory: 47610.7 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

Application closed

### Error Messages

None

### Error Logs

```shell
empty
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xNeffarion** [comment] 2022-08-18 14:41
I have the same issue.
Here is the terminal output when trying to run the appimage:

> 15:34:51.638 › Checking for update
15:34:51.873 › Update for version 1.6.5 is not available (latest version: 1.6.5, downgrade is disallowed).
[6071:0818/153451.897490:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[appimage-binfmt-bypass/bin] ERROR: child exited with code 5


System:  
> - openSUSE Tumbleweed
> - Kernel: 5.19.1
> - DE: GNOME 42.4
> - GPU: NVIDIA GeForce RTX 2080 Ti
> - CPU: Intel i7-10700K

I confirm that running firefly with --no-sandbox parameter fixes the problem

**Comment by rheinschiene** [comment] 2022-10-01 10:59
I have the same problem running AppImage Firefly on Ubuntu 22.04:
[2327:1001/124555.689920:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

Seems like this is an issue with Electron:
https://github.com/electron/electron/pull/31091

**Comment by erzwo** [comment] 2022-11-07 10:44
Update: Version 1.7.0 has this issue, as well.

**Comment by begonaalvarezd** [comment] 2023-09-20 13:40
Hi, is this still an issue in the latest version?

**Comment by rheinschiene** [comment] 2023-09-20 14:51
Yes, this is still an issue on Ubuntu 22.04 with version 1.7.5 of firefly. The shimmer version (2.1.5) is running without problems.

```
$ ./firefly-desktop-1.7.5.AppImage 
16:46:40.161 › Checking for update
16:46:40.387 › Update for version 1.7.5 is not available (latest version: 1.7.5, downgrade is disallowed).
[5687:0920/164640.886631:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

**Comment by begonaalvarezd** [comment] 2023-10-01 06:26
> Yes, this is still an issue on Ubuntu 22.04 with version 1.7.5 of firefly. The shimmer version (2.1.5) is running without problems.
> 
> ```
> $ ./firefly-desktop-1.7.5.AppImage 
> 16:46:40.161 › Checking for update
> 16:46:40.387 › Update for version 1.7.5 is not available (latest version: 1.7.5, downgrade is disallowed).
> [5687:0920/164640.886631:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
> Trace/breakpoint trap (core dumped)
> ```

I use Ubuntu 22.04 and I cant reproduce the issue, the app works well for me. Searching for the issue you have it seems like you can try running Firefly with the `--no-sandbox` flag, it looks like is a common Electron issue, could you please try it out? In any case, we will release very soon a new version which has code parity with Firefly Shimmer so i would guess the issue will be gone very soon

**Comment by rheinschiene** [comment] 2023-10-01 15:29
If I use the ``--no-sandbox`` parameter, Firefly starts as expected, so this is working as a workaround. I'am looking forward for the merge of both Firefly versions. :-)

**Comment by begonaalvarezd** [comment] 2023-10-02 07:57
> If I use the `--no-sandbox` parameter, Firefly starts as expected, so this is working as a workaround. I'am looking forward for the merge of both Firefly versions. :-)

Unfortunately we will not be able to merge both apps anytime soon because, even though iota will be upgraded to stardust, we then need to start working on iota 2.0 for shimmer 🙈 so we have to keep both apps separate for now.

I'll close the issue, thanks for replying and testing 🌷

**Closed by begonaalvarezd** 2023-10-02 07:57 UTC
Labels: bug report
