### ISSUE TITLE
Preload context error

### ISSUE THREAD

**Issue by manubrave** [iotaledger/firefly#1192] opened 2021-06-06 17:39 UTC
## Issue description
When starting the session of a profile I get an error.Briefly describe the issue. 
In the last transactions section, it comes out loading my iotas. But in the Balance section there is no iota
In firefly we have two users.
It only happens to me in one. The other user works perfectly

## Wallet version

Which version of wallet are you using?
Version 1.1.0
platform: macOS

- wallet version (version number, commit, or branch):
PlatformVersion: 10.15
PlatformArchitecture: X64

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)
Big sur
## Is it a repeatable issue?
I do not know

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

That the user can see their iota balance as well as the money that each iota is worth. And it works as normal

## Errors
Error type: Preload context error.
Error: Uncaught TypeError: Cannot read property `id` of undefined

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.
![Captura de pantalla 2021-06-06 a las 19 33 48](https://user-images.githubusercontent.com/85453135/120934504-c55aff00-c6fe-11eb-8afa-3acceabfce34.png)
![Captura de pantalla 2021-06-06 a las 19 34 05](https://user-images.githubusercontent.com/85453135/120934510-d146c100-c6fe-11eb-9206-ae2e49fe3508.png)
![Captura de pantalla 2021-06-06 a las 19 34 25](https://user-images.githubusercontent.com/85453135/120934517-d73ca200-c6fe-11eb-8a47-68b9463f540f.png)

**Comment by nicole-obrien** [comment] 2022-01-06 15:36
Duplicate of #1087

**Closed by nicole-obrien** 2022-01-06 15:36 UTC
Labels: type:bug, status:duplicate
