### ISSUE TITLE
[Bug report]: Latest Firefly wallet update failed

### ISSUE THREAD

**Issue by chinyueconsultancy** [iotaledger/firefly#7328] opened 2023-08-18 08:33 UTC
### Platform

Desktop

### Version

1.7.3

### Description

1.7.3 version of Firefly desktop failed to load.  Below is the failed report:

App Version: 1.7.3

platform: macOS
platformVersion: 11.7.6
platformArchitecture: x64
cpuCount: 16
totalMem: 16384.0 MB
freeMem: 174.1 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

### Expected behaviour

Latest Firefly desktop update loading correctly

### Actual behaviour

Latest Firefly desktop update NOT loading correctly

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Logs

```shell
App Version: 1.7.3

platform: macOS
platformVersion: 11.7.6
platformArchitecture: x64
cpuCount: 16
totalMem: 16384.0 MB
freeMem: 174.1 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by greg-olivier** [comment] 2023-08-18 08:56
+1

`App Version: 1.7.3

platform: macOS
platformVersion: 10.15.7
platformArchitecture: x64
cpuCount: 4
totalMem: 16384.0 MB
freeMem: 8279.4 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node`

**Comment by w4tt5old4t** [comment] 2023-08-18 09:25
+1

App Version: 1.7.3

platform: macOS
platformVersion: 10.13.4
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 7659.0 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

**Comment by MartinMueller-StudioMood** [comment] 2023-08-18 13:06
App Version: 1.7.3

platform: macOS
platformVersion: 11.2.2
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 232.7 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

**Comment by marc2332** [comment] 2023-08-18 14:35
Duplicate of https://github.com/iotaledger/firefly/issues/7324

**Closed by marc2332** 2023-08-18 14:35 UTC
Labels: bug report

**Comment by MartinMueller-StudioMood** [comment] 2023-08-20 15:44
when will you finally fix it???

**Comment by w4tt5old4t** [comment] 2023-09-18 08:40
wtf? when do you fix it?
You have to code an update that works for everyone!
when iota 2.0 will launch and not everyone is able to update, they will lose their tokens. 
so please, fix it and give us update that work!

**Comment by w4tt5old4t** [comment] 2023-09-18 09:04
ok, thank you. unfortunately it doesnot work for my macOS-version (i need that version because of some plugins for my DAW).

I have another mac with another macOX. that should work. but a have to install firefly. I have connected firefly with my Ledger. Well, the recovery seed is enough to recover my firefly-wallet (connected with Ledger) on another macOS?

thanks for your help!

**Comment by begonaalvarezd** [comment] 2023-09-18 09:23
> ok, thank you. unfortunately it doesnot work for my macOS-version (i need that version because of some plugins for my DAW).
> 
> I have another mac with another macOX. that should work. but a have to install firefly. I have connected firefly with my Ledger. Well, the recovery seed is enough to recover my firefly-wallet (connected with Ledger) on another macOS?
> 
> thanks for your help!

You can always recover your funds from 24 word mnemonic, ledger, or stronghold. On recovered profiles it can take a bit to sync and also to find all addresses and balances, if you are missing balances just go to settings > balance finder, and search couple of times so firefly can find all your addresses

**Comment by w4tt5old4t** [comment] 2023-10-09 10:23
I installed the firefly-wallet on a Mac with an OS that works for the firefly-wallet. I entered the 24 words, to recover my wallet, but the balance is 0.  I clicked the search-button many times, but nothing found. I noticed, that the adress to receive funds is different from the receive-adress of the old wallet...... 
If I open the old wallet on the old Mac there are more than 4,855 GI – the Assembly-balance (30.202,76) is gone now. Do I have to connect my Ledger Nano S to find the balance?
Can I send the GIs from the old wallet to the new one? 
What can I do? Please help! Thank you!
