### ISSUE TITLE
[Bug]: Node error the requested data was not found

### ISSUE THREAD

**Issue by marc2332** [iotaledger/firefly#7385] opened 2023-09-01 06:41 UTC
Sometimes Firefly throws an error like this:

`Node error the requested data <node-url> was not found`

It could be our fault or be something wrong in the SDK, it needs to be investigated nonetheless.

**Comment by begonaalvarezd** [comment] 2023-09-18 08:53
@marc2332 @cpl121 any updates on this error? Is it still happening?

**Comment by begonaalvarezd** [comment] 2023-09-19 16:12
> Today I have not received this error again @begonaalvarezd

Lets keep an open eye, otherwise we close it in a couple of days

**Comment by begonaalvarezd** [comment] 2023-10-01 07:31
I havent been able to reproduce this issue anymore, closing due to inactivity. Please reopen if necessary @marc2332

**Closed by begonaalvarezd** 2023-10-01 07:31 UTC
Labels: bug report
