### ISSUE TITLE
Trying to understand why my Firefly is not showing my IOTA balance, just Shimmer

### ISSUE THREAD

**Issue by MFL101** [iotaledger/firefly#7034] opened 2023-06-23 23:38 UTC
### Platform

Desktop

### Version

2.0.0

### Description

I see a shimmer balance but no IOTA wallet or balance?

Haven't booted it up in a while. Trying to figure out what happened to my IOTA

### Expected behaviour

I expect to see balance of both assets

### Actual behaviour

I see only Shimmer

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

It's produced every time I open the app

### Operating System

Windows

### Diagnostics

```shell
Version 
Language: en
Currency: USD
Node list: https://api.shimmer.network
Platform: win32
Platform Version: 10.0.22621
Platform Architecture: x64
CPU Count: 6
Total Memory: 32572.6 MB
Free Memory: 9848.6 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment] 2023-06-26 07:50
Hi, we curently have 2 versions of Firefly, one for IOTA and one for Shimmer. We dont display both balances under the same app at the moment.
You can download both versions in the official Firelfy website https://firefly.iota.org/
- Firefly Shimmer: latest version v2.1.3
- Firefly IOTA: latest version v1.0.6

I'll close the issue since its not a bug in the app
Please feel free to reach again if you encounter an issue

**Closed by begonaalvarezd** 2023-06-26 07:50 UTC
Labels: bug report
