### ISSUE TITLE
[UI] Transaction status not updated after transaction confirmed

### ISSUE THREAD

**Issue by georg90** [iotaledger/firefly#1074] opened 2021-04-29 19:45 UTC
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

1.0.0

## System specification

What is your operating system?

Windows 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Sent transaction
2. Click on details for transaction before it confirmed (be quick, it's Chrysalis!)
3. See notification that transaction confirmed, but see pending status remaining

## Expected behaviour

Status should adopt "confirmed"

## Actual behaviour

![image](https://user-images.githubusercontent.com/6489464/116608912-07d93100-a934-11eb-9733-3a9f948b2f91.png)

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Tuditi** [comment] 2022-08-02 15:38
I'm closing this down, since the issue is outdated. If it is still present in the current Firefly version (1.6.5), please reopen it!

**Closed by Tuditi** 2022-08-02 15:38 UTC
