### ISSUE TITLE
Can' t unlock wallet, logout does not work, closing settings does not work

### ISSUE THREAD

**Issue by axelf** [iotaledger/firefly#1027] opened 2021-04-25 22:13 UTC
## Issue description

If i click on the circle left down and then on logout nothing happens. After that i cant click anywhere. If i want to unlock the wallet nothing happens after entering my password. Changing the settings does not work. After clicking the x i also cant click anywhere

## Wallet version

Firefly 1.0.0, commit 484832b

## System specification

Mac oS Catalina 10.15.7

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. enter pin
2. go to user icon left bottom
3. klick log out

1. enter pin
2. go to user icon and klick settings
3. enter setting and close

1. enter pin
2. right bottom unlock wallet
3. enter password
4. nothin happens

## Expected behaviour

log out from wallet, change setting, can unlock wallet

## Actual behaviour

nothing happens. I can't click anywhere. The app does not respond.

#### This is the Error Log:

Mon, 26 Apr 2021 08:21:42 GMT
ClientError: `Response error with status code 521: <html>
<head><title>521 Origin Down</title></head>
<body bgcolor="white">
<center><h1>521 Origin Down</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>

Mon, 26 Apr 2021 08:08:37 GMT
ClientError: `Response error with status code 521: <html>
<head><title>521 Origin Down</title></head>
<body bgcolor="white">
<center><h1>521 Origin Down</h1></center>
<hr><center>cloudflare-nginx</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"645e52fb9ca369bc","version":"2021.4.0","si":10}'></script>
</body>
</html>

Sun, 25 Apr 2021 22:12:06 GMT
ClientError: `Response error with status code 521: <html>
<head><title>521 Origin Down</title></head>
<body bgcolor="white">
<center><h1>521 Origin Down</h1></center>
<hr><center>cloudflare-nginx</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"si":10,"rayId":"645ae9331fb40843","version":"2021.4.0"}'></script>
</body>
</html>

Sun, 25 Apr 2021 22:12:05 GMT
ClientError: `Response error with status code 521: <html>
<head><title>521 Origin Down</title></head>
<body bgcolor="white">
<center><h1>521 Origin Down</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>

Sun, 25 Apr 2021 21:31:39 GMT
ClientError: `Response error with status code 521: <html>
<head><title>521 Origin Down</title></head>
<body bgcolor="white">
<center><h1>521 Origin Down</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>

Sun, 25 Apr 2021 21:07:26 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 25 Apr 2021 21:07:25 GMT
ClientError: `Response error with status code 521: <html>
<head><title>521 Origin Down</title></head>
<body bgcolor="white">
<center><h1>521 Origin Down</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>

**Comment by bompi88** [comment] 2021-04-26 06:14
I experience a similar thing.. I've created multiple profiles. The first profile I created suddenly stopped working. I can't login to the profile, because the login animation goes on forever. If I click `Firefly->Errors` during this animation I'll get "logged in", but nothing seems to work as it should.

**Comment by cvarley100** [comment] 2021-04-26 10:59
This should be fixed now.

**Comment by HOlotti** [comment] 2021-04-26 11:01
I had the same problem, but i can confirm that the issue is fixed!

**Closed** 2021-04-26 11:58 UTC
Labels: bug

**Comment by axelf** [comment] 2021-04-26 18:15
Yeah, it is fixed, thank you.
