### ISSUE TITLE
[Bug report]: CRASH after download new version 1.7.3

### ISSUE THREAD

**Issue by aposada** [iotaledger/firefly#7352] opened 2023-08-23 15:55 UTC
### Platform

Desktop

### Version

1.7.3

### Description

Not work in my Bigsur... is like only compiled for macOS 13.0
what happened with other computers? 

### Expected behavior

Open normally as usual

### Actual behavior

Crass after opening it

App Version: 1.7.3

platform: macOS
platformVersion: 11.6.6
platform architecture: x64
cpuCount: 8
totalMem: 24576.0 MB
freeMem: 304.7 MB

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Diagnostics

```shell
App Version: 1.7.3

platform: macOS
platformVersion: 11.6.6
platformArchitecture: x64
cpuCount: 8
totalMem: 24576.0 MB
freeMem: 304.7 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

Non-responsive

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment] 2023-08-23 16:22
Duplicate of https://github.com/iotaledger/firefly/issues/7324

**Closed by begonaalvarezd** 2023-08-23 16:22 UTC
Labels: bug report
