### ISSUE TITLE
My Reciving Addresses keep changing automatically (i dont want them to)

### ISSUE THREAD

**Issue by TrueChessknock** [iotaledger/firefly#640] opened 2021-03-22 18:40 UTC
## Issue description

My Recieving addresses keep changing automatically once i recieve some funds, is it going to happen in full release?
Cause since they are reusable, i dont want them to change (for me there is no much point to change it after every transaction i do) and if  I decide to change it, i can do it manually by myself (by clicking reload icon) 

And whether it will still be automatically changing in the future or manually, I think it would be nice to see all My recieving addresses in like Folding list (which may contain last 3-5 addresses and I i would like to see them all, nice to have option to see them all.. without digging in transaction history)

## Wallet version

0.3

What is your operating system?

Windows

## Is it a repeatable issue?

Y

**Comment by 94jaku** [comment] 2021-03-22 19:04
Agree, vote up :)

**Comment by MiKeF05** [comment] 2021-03-22 19:39
Everytime you receive a transaction on a receive address and you click again on receive you get a new one. But you can use the address before for other transactions of course.

For example an online shop could generate one address and use the exact same address for many transactions.

**Comment by cvarley100** [comment] 2021-03-30 16:41
We do this for privacy reasons. If we present the same receive address every time, all users you transact with will know your full balance. You can of course reuse addresses if you want to (by storing an address somewhere out of firefly).

**Comment by cvarley100** [comment] 2021-03-31 16:15
We will be adding an address history in the next update.

Closing this issue as a duplicate of #725

**Closed by cvarley100** 2021-03-31 16:15 UTC
Labels: enhancement
