### ISSUE TITLE
"Problem with shortcut" after in-app update

### ISSUE THREAD

**Issue by cyclux** [iotaledger/firefly#577] opened 2021-03-21 14:22 UTC
## Issue description

On Windows it can happen that after the in-app update we get following shortcut issue:
![image](https://user-images.githubusercontent.com/5097913/111908045-fd379c00-8a57-11eb-868f-158518a813d7.png)

If you keep the shortcut (click "no") and once again start the app it works as intended.

## Wallet version

0.2.0 -> 0.2.1

## System specification

Windows 10 Version 10.0.19042 Build 19042

## Is it a repeatable issue?

Probably

## Steps To reproduce the issue

In-app update procedure.
Miss or ignore the "restart prompt".
Close app.
Restart app relatively quickly.
Further investigation needs to check if the shortcut issue only happens if you quickly manually restart the app or if is always happens once, independent of the restart time.

## Expected behaviour

No "Problem with shortcut" after manually restarting the app during in-app update procedure.
Maybe keep the "app restart needed" prompt open, so that users can't miss it.

**Comment by rafaeldjpbrochado** [comment] 2021-03-22 23:58
Can confirm this is still an issue. Happened just now when I tried to update from v0.3.0 to v0.3.1.

**Comment by cyclux** [comment] 2021-03-23 00:08
So this time I waited a bit longer to restart the app, and the issue did not occur. I recognized a short "flash" of my taskbar shortly after closing Firefly, probably in this moment the update process got finally completed.

**Comment by Tuditi** [comment] 2022-08-02 15:10
I'm closing this down, since the issue is outdated. If it is still present in the current Firefly version (1.6.5), please reopen it!

**Closed by Tuditi** 2022-08-02 15:10 UTC
Labels: bug report, os:windows
