### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by metasilver** [iotaledger/firefly#2752] opened 2022-04-05 08:42 UTC
### Platform

Desktop, Mobile

### Version

1.3.3

### Description

App Version: 1.3.3

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 2
totalMem: 7915.5 MB
freeMem: 4365.6 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NETWORK_CHANGED

### Expected behaviour

An error occurs once in a while.
no problem to use

### Actual behaviour

Even after updating, the error doesn't go away.
Laptops used exclusively for firefly

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

App Version: 1.3.3

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 2
totalMem: 7915.5 MB
freeMem: 4365.6 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NETWORK_CHANGED

### Error Logs

```shell
App Version: 1.3.3

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 2
totalMem: 7915.5 MB
freeMem: 4365.6 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NETWORK_CHANGED
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment] 2022-04-06 12:43
I will close this issue, since it might be fixed in 1.4.1 and this cannot be reliably reproduced. If this issue is encountered again after 1.4.1, feel free to open it again!

**Closed by Tuditi** 2022-04-06 12:43 UTC
Labels: bug report
