### ISSUE TITLE
Wrong balance in graph / chart during internal transfer

### ISSUE THREAD

**Issue by nfr1974** [iotaledger/firefly#762] opened 2021-03-27 22:55 UTC
## Issue description

During internal transfer between wallets the graph / chart is displayed with the wrong amount

## Wallet version

Firefly
V0.3.1

## System specification

What is your operating system?

Windows 10 Home 10H2

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.just send MAX internaly to other wallet
2.
3.

## Actual behaviour

Wrong value in graph / chart
[Wrong chart - graph during internal transfer.pdf](https://github.com/iotaledger/firefly/files/6216562/Wrong.chart.-.graph.during.internal.transfer.pdf)

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Danlino** [comment] 2021-04-20 17:31
https://ibb.co/1fPbbb0

**Comment by cvarley100** [comment] 2021-05-05 19:45
Duplicate of #864

**Closed by cvarley100** 2021-05-05 19:45 UTC
Labels: bug
