### ISSUE TITLE
Trying to transfer IOTA from Binance to Firefly and getting error- Withdrawal address is wrong

### ISSUE THREAD

**Issue by Cryptoredsun** [iotaledger/firefly#1144] opened 2021-05-10 14:49 UTC
## Issue description

**Trying to transfer IOTA from Binance to Firefly and getting error- Withdrawal address is wrong.**

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch): **V1.1.0**

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

**Windows 10**

## Is it a repeatable issue?

Y/N
**Yes**

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. **In Binance if you paste the receiving address generated by Firefly, binance says that the entered address is wrong for IOTA.**
2.
3.

## Expected behaviour

Describe what you expect to happen.

**In Binance if you paste the receiving address generated by Firefly, binance should accept the address.**

## Actual behaviour

Describe what actually happens.

**In Binance if you paste the receiving address generated by Firefly, binance says that the entered address is wrong for IOTA.**

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Screenshots attached. Please respond urgently as binance gave me very limited time before they airdrop my assets in binance.**

![Binance IOTA Withdrawal Issue](https://user-images.githubusercontent.com/83967462/117678462-68ab0980-b17d-11eb-9897-d803c9936322.JPG)
![Firefly app receive screenshot](https://user-images.githubusercontent.com/83967462/117678470-6ba5fa00-b17d-11eb-8dc2-d7bb9fb25155.JPG)

**Comment by Cryptoredsun** [comment] 2021-05-11 18:45
I don't have that much time now. Binance gave me 48hrs to withdraw my IOTA or else they will suspend access to binance meaning I lose all of the IOTA. Can you tell me if there are any other wallets or other avenues which accept trabsferring IOTA using BSC network?

**Comment by Cryptoredsun** [comment] 2021-05-11 21:29
I tried requesting them to extend the timeline to close it but I haven't heard back from them. Also, I even tried to convert IOTA to any other coin such as ETH or BTC but IOTA is not even listed in the dropdown menu to choose to convert from. Please see the screenshots below.

![binance 48hr withdrawal limit](https://user-images.githubusercontent.com/83967462/117887250-68466780-b27e-11eb-8718-d304869c4246.JPG)

![binance chat IOTA](https://user-images.githubusercontent.com/83967462/117887268-70060c00-b27e-11eb-8688-0f946efe9683.JPG)

![IOTA not available in dropdown](https://user-images.githubusercontent.com/83967462/117887295-7a280a80-b27e-11eb-92ed-18bc2dc7d659.JPG)

**Comment by rajivshah3** [comment] 2021-05-12 01:04
Duplicate of #1119

**Closed by rajivshah3** 2021-05-12 01:04 UTC
Labels: bug
