### ISSUE TITLE
[Bug]: Error message when starting Firefly wallet without active internet connection

### ISSUE THREAD

**Issue by kaktus2** [iotaledger/firefly#2312] opened 2022-02-10 18:31 UTC
### Issue description

if you start the firefly wallet without an active internet connection you get an error message!

![Unbenannt2](https://user-images.githubusercontent.com/2196583/153472984-3b8a71f7-2ffd-4140-bb1f-a835038f8dc5.png)

### Expected behaviour

Login screen

### Actual behaviour

error screen.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. disconnect your internet connection
2. start firefly wallet
3. get error message
4. close firefly wallet
5. start with point 2. again

### Duplicate declaration

- [x] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment] 2022-02-13 10:40
These errors will most likely be swallowed in one of the next versions. You should be able to use Firefly like before.

**Comment by kraftjs** [comment] 2022-02-16 20:19
Exiting the error message and reconnecting internet fixes issue without needing to restart application. Exiting the error and logging into profile prompts the user with a valid notice: `Could not find DNS resolution for node`.

Closing this issue because behavior is normal.

**Closed by kraftjs** 2022-02-16 20:19 UTC
Labels: type:bug, status:invalid

**Comment by kaktus2** [comment] 2022-02-16 20:49
> Exiting the error message and reconnecting internet fixes issue without needing to restart application. Exiting the error and logging into profile prompts the user with a valid notice: `Could not find DNS resolution for node`.
> 
> Closing this issue because behavior is normal.

Yes but it would be less confusing if it would be an info box  with the hint that no internet connections is present instead of an error exception...

**Comment by kraftjs** [comment] 2022-02-16 20:57
I am on the same platform and version as you. When reproducing your error I receive a ERR_INTERNET_DISCONNECTED exception. Can you re-confirm that you are not receiving that error exception? Are there any additional steps you are taking?

![image](https://user-images.githubusercontent.com/72045705/154355168-552054f2-0214-455b-b067-182ed10e8cdc.png)
