### ISSUE TITLE
Keyboard Search in Drop-Down Menus

### ISSUE THREAD

**Issue by Oskar-F** [iotaledger/firefly#644] opened 2021-03-22 19:11 UTC
## Description

In drop-down menus, make keyboard input available, in order to make finding the desired value quicker.

## Motivation

Right now it's difficult to find the right value in drop-down menus with many items.

## Requirements

When opening the drop-down, keyboard input should make the menu jump to the desired value.

Example:
In "All Settings -> General Settings -> Language", when clicking the drop-down and typing "G" the menu should jump to the first item starting with the letter "G" ("German"). When typing "Gr" the menu should jump to the first item starting with the letters "Gr" ("Greek"). Etc.

## Are you planning to do it yourself in a pull request?

No.

**Comment by cvarley100** [comment] 2021-04-11 01:23
Duplicate of #832

**Closed by cvarley100** 2021-04-11 01:23 UTC
Labels: feature-request
