### ISSUE TITLE
Allow smaller window-size

### ISSUE THREAD

**Issue by brunnerm4x** [iotaledger/firefly#993] opened 2021-04-21 20:08 UTC
## Description

Allow small window size, probably with mobile-like interface when under specific size.

## Motivation

With current version, on small screen with low resolution (1366x768) the wallet minimum size is almost full display width and because of taskbar and title-bar a bit more than the available height (On Devuan Linux with MATE Desktop). Also nice when using parallel to other applications.

## Requirements

1. Allow smaller windows
2. Optimize displayed content for very small sizes

## Are you planning to do it yourself in a pull request?

No

**Comment by cvarley100** [comment] 2021-04-29 12:58
Duplicate of #248

**Closed by cvarley100** 2021-04-29 12:58 UTC
Labels: enhancement, ux
