### ISSUE TITLE
[Windows 10]Profile Name Error and White Screen Issue After Seedvault/Seed Use

### ISSUE THREAD

**Issue by Grachas** [iotaledger/firefly#992] opened 2021-04-21 20:06 UTC
## Issue description

At first when you enter a profile name you get an error then if you click continue with the same name you can proceed. After attempting to use the seedvault created from Trinity or 81 character long seed, we get an empty unresponsive whitescreen.

Edit: Profile name issue might be due to the directory Firefly installed includes user name having "ğ" letter. 

## Wallet version

Desktop 1.0.0 

## System specification

Windows 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Enter your seed or use seedvault.
2. Press continue.
3. See whitescreen.

## Expected behaviour

We expected to see the amount to be migrated.

## Actual behaviour

Whitescreen occurs.

## Errors

![Screen1](https://user-images.githubusercontent.com/82975253/115614241-20bf6200-a2f6-11eb-9e65-ac5ca00cab42.PNG)
![Screen2](https://user-images.githubusercontent.com/82975253/115614245-2157f880-a2f6-11eb-85aa-e60a3a5c4069.PNG)

**Comment by Tombaaa** [comment] 2021-04-22 13:38
This happend to me too, I use a user name with a special character 'ä', the user directory where the files are located contain this special character too. 

See user path from Diagnostic:
User Path: C:\Users\Bänni\AppData\Roaming\Firefly

**Comment by Grachas** [comment] 2021-04-22 16:40
To be honest I'd rather not go through the hoops of changing the username folder in Windows 10. And it appears many people are encountering this issue so far, any news from the IF side?

**Comment by rajivshah3** [comment] 2021-04-26 20:43
@Grachas we're working on a patch for the issue

**Comment by rajivshah3** [comment] 2021-04-26 20:44
Closing as duplicate of #1015

**Closed by rajivshah3** 2021-04-26 20:44 UTC
Labels: bug
