### ISSUE TITLE
error when copying address

### ISSUE THREAD

**Issue by jesusmarianuin** [iotaledger/firefly#1842] opened 2021-12-21 21:35 UTC
### Issue description

error when copying address:
App Version: 1.3.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 12
totalMem: 32448.3 MB
freeMem: 23057.6 MB

Error Type: Callback Error syncAccounts

TypeError: Cannot read property 'depositAddress' of undefined
    at file:///C:/Users/jesus/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2112599
    at Array.map (<anonymous>)
    at Bs (file:///C:/Users/jesus/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2112538)
    at onSuccess (file:///C:/Users/jesus/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2110189)
    at Function.t.<computed>.<computed> (file:///C:/Users/jesus/AppData/Local/Programs/desktop/resources/app.asar/public/build/index.js:2:2108070)

### Firefly version

1.3.0

### OS details

Windows 10 pro  20H2 19042.1415

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. Clic in copy address
2. Error

### Expected behaviour

Copy address

### Actual behaviour

¿?

**Comment by MiKeF05** [comment] 2021-12-24 11:04
@jesusmarianuin Can you try to restore your profile either with the 24 words or the stronghold backup? If you use a ledger then you need the ledger to restore it.

**Comment by rajivshah3** [comment] 2022-01-03 23:45
The stacktrace indicates that this may be a duplicate of #1840

**Closed by rajivshah3** 2022-01-03 23:45 UTC
Labels: type:bug
