### ISSUE TITLE
button "latest transactions" automaticaly creates new receiving addresses for all accounts

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#578] opened 2021-03-21 16:15 UTC
## Issue description
I thought we could keep one fixed receiving address per account, but wondered that i saw them changing without a recognisable pattern.
I did the following test on a total fresh profile
before every tx i saved the receiving addresses of the account
-request from faucet to acc1
-create acc2
request from faucet to acc2
-transfer from acc1 to acc2
-transfer from acc2 to acc1
- always 3 Mi tx value
- i ping ponged this several times and recognized that whenever i pushed "latest transactions" in the main view because the t x did not arrive in time i had afterwards different receiving addresses

## Wallet version

Firefly v0.2.1
Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64
CPU Count: 4
Total Memory: 6082.5 MB
Free Memory: 2089.1 MB
User Path: C:\Users\Amedw\AppData\Roaming\Firefly

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

see above

## Expected behaviour
1.) i expected the whole cool thing of chrysalis where reusable addresses so 1 address fixed for 1 account that i can use forever to receive and send tokens.

## Actual behaviour
addresses change if i push a button that has no indication that addresses will be changed - this button seems to be a refresh button to get updated tx states and balances.
Also if we can generate new addresses for an account - how do we keep track of that addresses? Only if we write them down and look in explorer what happens to them? 
Thats not what i had expected to be.
If addresses can change we need a function / a log - of all addresses related to one account in the wallet
## Errors
no errors

this is the file with all addresses that where generated per account during the sending forth and back between 2 accounts"
[acc address change.txt](https://github.com/iotaledger/firefly/files/6177841/acc.address.change.txt)

thats the button that changes the addresses:
![image](https://user-images.githubusercontent.com/77154511/111912235-bd96a180-8aa3-11eb-9d4f-089a8504642b.png)

**Comment by Tuditi** [comment] 2022-08-04 09:12
This requires a broader discussion, since it is possible to reuse your address (you could send to an already used address and it would show up in your balance). [Due to privacy reasons](https://en.bitcoin.it/wiki/Address_reuse), this is not recommended which is why currently Firefly automatically switches addresses once they have been used.

I'll close this down, since the button works as intended. The confirmation of a new transaction triggers address generation. The refresh button looks for new transactions or transaction state changes, which is why it looks like the refresh button triggers it.

Feel free to reopen this or convert it to a discussion if you want to add something to the topic!

**Closed by Tuditi** 2022-08-04 09:12 UTC
Labels: bug report, priority:4
