### ISSUE TITLE
Preload Context Error

### ISSUE THREAD

**Issue by densnet8888** [iotaledger/firefly#1138] opened 2021-05-08 19:39 UTC
App Version: 1.1.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 16
totalMem: 16314.6 MB
freeMem: 7051.1 MB
userPath: C:\Users\Win10\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at C:\Users\Win10\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:165586
    at C:\Users\Win10\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\Win10\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197594)
    at C:\Users\Win10\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:191379

**Comment by cvarley100** [comment] 2021-05-10 11:00
Duplicate of #1087

**Closed by cvarley100** 2021-05-10 11:00 UTC
Labels: bug
