### ISSUE TITLE
[Bug report]: I am having an issue with rewards  

### ISSUE THREAD

**Issue by Wdmoore01** [iotaledger/firefly#8582] opened 2024-07-16 04:42 UTC
### Version

Firefly 2.0.11

### Description

I have approximately 1450 IOTA tokens and have had them stal=ked for about 6 weeks now in this wallet and I have voted with my voting points successfully as well!  But I have recieved no Rewards as yet and I have contacted support about 6 times and have recieved no soultions and little help as yet.  If i remove my Firefly wallet and reload it with the seed phrase, will this fix the issue?

### Expected behaviour

I cam to deposit tokens here on June1 and june 8th and immediately staked them for governance according to the instructions i had at the time.  I deposited approx 1450 Iota tokens. but in about 6 weeks, and 1 governance voting session, I have yet to see any changes in my totals nor a mention of a reward at a different location.

### Actual behaviour

![Firefly -01](https://github.com/user-attachments/assets/df1c7657-407c-4cff-8cba-3defadd6c771)
![Firefly -03](https://github.com/user-attachments/assets/01d2d9a0-7f8d-4bec-8b91-4dbc19c0c646)

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Every time I open the wallet, no changes and I have tried to find any appropriate choices or diagnostics to resolve the issue, but i have found no help in the multiple efforts of support contacts. After being advised to purchase IOTA and to bring them here to stake the tokens, I have been completely unsuccesful in gaining any rewards for my POS staking nor for my governance votes.  

### Operating System

Windows

### Diagnostics

```shell
App Name: Firefly
Version 2.0.11
Language: en
Currency: usd
Node list: https://api.stardust-mainnet.iotaledger.net,https://iota-node.tanglebay.com
Platform: win32
Platform Version: 10.0.19045
Platform Architecture: x64
CPU Count: 8
Total Memory: 32477.8 MB
Free Memory: 23369.8 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

NO error messages. Just no rewards so far i was told they would arrive every 14 days.

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment] 2024-07-18 09:30
There is no staking at the moment in L1, so there is no rewards whatsovever you could get from the layer 1 (mainnet). If you are staking in layer 2 (EVM) you should contact the platform you used to stake.

The vesting page in your screenshot corresponds to the IOTA Airdrop vesting schedule I already explained to you in the other ticket you opened, that airdrop happened in October 2023 as part of the new tokenomics derived from the supply increase during the merge (October 4 2024) 

There is no active staking event since more than a year ago, locking funds for voting power is not to get rewards but to participate in the governance framework to vote on decisions on the network , like the current active vote we have ongoing https://govern.iota.org/t/igp-0005-a-proposal-for-supercharging-the-expansion-of-iota-evm-growth/1756/1

I'll close this issue as duplicate of https://github.com/iotaledger/firefly/issues/8549

**Closed by begonaalvarezd** 2024-07-18 09:30 UTC
Labels: bug report
