### ISSUE TITLE
Can't set up and verify pin code on Linux Manjaro 20.2.1

### ISSUE THREAD

**Issue by Foksler** [iotaledger/firefly#931] opened 2021-04-19 18:51 UTC
## Issue description

Can't verify pin code

## Wallet version

Which version of wallet are you using?

- v 0.4.0

## System specification

Linux Manjaro 20.2.1

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Install manjaro 20.2.1
2. instal firefly 0.4.0 
3. try to register, on pin code verify action -> nothing happens

## Expected behaviour

After pin set up and after i verify pin -> registration must be continued
## Actual behaviour

No error, after you try to verify you pin with Confirm pin code button , input became empty.

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.
Error log is empty

**Comment by rajivshah3** [comment] 2021-04-20 16:01
Please see https://github.com/iotaledger/firefly/issues/243 and let us know if that solves the issue

**Comment by antalm** [comment] 2021-04-20 17:08
I think that error log with instructions on installing the missing libsecret package should be added, like it was in Trinity. That would help users to resolve the problem.

Foksker, please try this:
sudo pacman -S libsecret

**Comment by Foksler** [comment] 2021-04-24 16:36
@rajivshah3 @antalm 
hello, thx for advice, but it didn't helped(
still not working and no errors

**Comment by cvarley100** [comment] 2021-05-05 19:47
Duplicate of #243

**Closed by cvarley100** 2021-05-05 19:47 UTC
Labels: bug
