### ISSUE TITLE
My balance is visible on the message explorer site but not in the Firefly wallet

### ISSUE THREAD

**Issue by shudai79** [iotaledger/firefly#1701] opened 2021-12-08 20:43 UTC
### Issue description

I did transfer a certain amount of IOTA from BITRUE to the Firefly wallet. However, the balance is not visible in the wallet. While I could confirm that the balance was received on the address on the message explorer website. 

The  network shows as disconnected in the wallet and I do get an error message when trying to find the balance: error.node.chrysalis.NodeInactive.

### Firefly version

v1.20

### OS details

Windows 10 Enterprise

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Login
2. All settings
3. Balance finder
4. Find balance
5. Search balance

### Expected behaviour

Show Balance

### Actual behaviour

No Balance is shown, 0Mi.

### Errors

error.node.chrysalis.NodeInactive.

**Comment by MiKeF05** [comment] 2021-12-08 21:11
Hello,

I think this is most likely a bug in Firefly. This will be fixed with the new release. In the meantime you can try to create a new profile and restore your profile with your 24 words. If you use a ledger then use the ledger to restore your profile.

**Comment by shudai79** [comment] 2021-12-09 08:10
Thanks a lot. When you say create a new profile, you mean deleting the existing one and using the backup?

**Comment by MiKeF05** [comment] 2021-12-09 11:19
Yeah just try to create a new profile with your backup file. The other profile hab ne deleted after you have successfully restored your wallet

**Comment by MiKeF05** [comment] 2021-12-19 13:47
@shudai79 Could you solve your issue?

**Comment by shudai79** [comment] 2021-12-21 22:53
No, I still have the same issue. Even with the new version 1.3. What should I do?

**Comment by shudai79** [comment] 2021-12-21 22:56
The network does not stay connected.

**Comment by shudai79** [comment] 2021-12-21 23:08
Tue, 21 Dec 2021 23:06:55 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): operation timed out`

Tue, 21 Dec 2021 23:06:45 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: dns error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)`

Tue, 21 Dec 2021 23:06:45 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: dns error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)`

Tue, 21 Dec 2021 23:06:45 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: dns error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)`

Tue, 21 Dec 2021 23:06:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: dns error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)`

Tue, 21 Dec 2021 23:06:35 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: No such host is known. (os error 11001)`

Tue, 21 Dec 2021 23:06:35 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: dns error: No such host is known. (os error 11001)`

Tue, 21 Dec 2021 23:06:35 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: dns error: No such host is known. (os error 11001)`

**Comment by MiKeF05** [comment] 2021-12-22 18:23
Can you try to change the node to 
https://mainnet-node.tanglebay.com

**Comment by MiKeF05** [comment] 2021-12-24 11:19
@shudai79 Were you able to resolve your issue? But it looks like there is a DNS error from your OS.

**Comment by Tuditi** [comment] 2022-08-02 15:37
I'm closing this down, since the issue is outdated. If it is still present in the current Firefly version (1.6.5), please reopen it!

**Closed by Tuditi** 2022-08-02 15:37 UTC
Labels: bug report
