### ISSUE TITLE
[Task]: Ditch JavaScript

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3778] opened 2022-07-04 16:07 UTC
### Task description

Replace all existing js code with ts code

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment] 2022-07-21 16:19
This is a duplicate of this [task](https://github.com/iotaledger/firefly/issues/2081)

**Closed** 2022-07-22 08:31 UTC
Labels: status:duplicate, package:desktop, package:shared
