### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by corbo** [iotaledger/firefly#1000] opened 2021-04-22 07:00 UTC
## Issue description

After migrating existing wallet or creating a new wallet the main panel stays blank

## Wallet version

Which version of wallet are you using?

- wallet version 1.0.0

## System specification

What is your operating system?

Win 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. (Re)Start firefly (from a previous session the preferences are remembered correctly)
2. Import kbxk seedvault process
3.  After the message that the wallet was restored correctly the screen stays blank
4.  The upper-left system menu kinda works. From the options only the About and Logoff/exit ones work

## Expected behaviour

See  a proper working version of Firefly

## Actual behaviour

Main screen stays blank

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by corbo** [comment] 2021-04-22 08:39
The "upper-left system menu" works properly prior to the blank main panel condition. So after starting up and before going through a migration or new wallet procedure it behaves as axpected. The blank main panel condition also affects the check-for-updates and error-log (display) functions.

**Comment by dekuyer** [comment] 2021-04-22 09:27
Same issue here. 
see video. 
[Firefly 2021-04-22 11-19-13.zip](https://github.com/iotaledger/firefly/files/6357112/Firefly.2021-04-22.11-19-13.zip)

**Comment by Tombaaa** [comment] 2021-04-22 13:40
dekuyer, can you past your diagnostic here (see screenshot where to find it)
![image](https://user-images.githubusercontent.com/77152394/115724262-1302ee80-a381-11eb-8ef8-481da3ed8853.png)

**Comment by dekuyer** [comment] 2021-04-22 13:58
> dekuyer, can you past your diagnostic here (see screenshot where to find it)

Tombaa, as you can see on the printscreen I can open the menu and click on 'foutrapportages', but when i click it will not show the diagnostic pop up en keeps on being a blank screen. 

![image](https://user-images.githubusercontent.com/83006412/115725618-4c882980-a382-11eb-9a2c-ee4976da8eaf.png)

I also saw another issue #1005 that is about the same problem. Here the user said it won't happen in english, so I installed english as a language. This works fine.

But if I start firefly again and change the settings to Dutch (before i log in)  i get stuck in an earlier stage trying to get in the wallet. I keeps hanging after putting in the pincode. 

 So i think both issue are related to the dutch language settings. 

I'have put in a video of me trying to login after setting the language back to dutch.

[Firefly 2021-04-22 15-53-21.zip](https://github.com/iotaledger/firefly/files/6358826/Firefly.2021-04-22.15-53-21.zip)

**Comment by gitrodriguez09** [comment] 2021-04-24 05:38
Hello good day. I present the same problem of the blank interface. After updating Firefly, it restarts asking for all the steps for creating a Wallet. At the point of Migrating or restoring a Wallet, I dragged the Wallet Backup copy before updating it. The result is always the same regardless of the Language you select.
![Firefly-2021-04-24 07-37-10](https://user-images.githubusercontent.com/79043251/115948705-fcb77880-a4cf-11eb-9fa2-c83c61d11654.png)

**Comment by Tombaaa** [comment] 2021-04-26 13:19
@gitrodriguez09 please copy/past your Diagnosticos, thanks

**Comment by NHL-19** [comment] 2021-04-26 20:08
Same issue here. Starting with a fresh install, after entering the 81-character seed, the screen goes blank. There is a small menu top left, but nothing happens when I click "foutenlogboek" (diagnostics) or anything else for that matter. I'm using Dutch language. The behaviour can easily be reproduced (if you like typing 81 character strings multiple times ;-))
Changing the language to English solved the problem.

**Comment by rajivshah3** [comment] 2021-04-26 20:42
Closing as duplicate of #1005

**Closed by rajivshah3** 2021-04-26 20:42 UTC
Labels: bug
