### ISSUE TITLE
Address memory

### ISSUE THREAD

**Issue by TrueChessknock** [iotaledger/firefly#638] opened 2021-03-22 18:30 UTC
## Description
Add feature to remember any address on my choice (like if i tick the box, to let wallet know to remember this address while sending it first time) so it can be chosen somewhere in future transactions, by choosing it in the address input window, like popup menu way

Briefly describe the feature that you are requesting.

## Motivation
usefull in a lot of other wallets like metamask. Obvi

## Requirements

Write a list of what you want this feature to do.

1.
2.
3.

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No.

**Comment by rafaeldjpbrochado** [comment] 2021-03-25 12:20
Duplicate of/related to https://github.com/iotaledger/firefly/issues/497.

**Comment by obany** [comment] 2021-03-29 10:33
Closing for duplicate

**Closed by obany** 2021-03-29 10:33 UTC
