### ISSUE TITLE
Can't see a hidden wallet (Ledger)

### ISSUE THREAD

**Issue by YTC329** [iotaledger/firefly#2011] opened 2022-01-04 05:45 UTC
### Issue description

I created an empty wallet in the previous version (v1.3.1) of my Ledger Firefly wallet, I then hid the wallet.
Recently, I updated my Firefly to v 1.3.2 and I can't see the hidden wallet after I click "show hidden wallets". 
So now I can't generate a new wallet because that hidden one is empty. Thanks    

### Firefly version

1.3.2

### OS details

Window 11

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open Firefly
2. Setting
3. Click "show hidden wallets"
...

### Expected behaviour

I should be able to see the hidden wallet

### Actual behaviour

No hidden wallet has shown up

**Comment by MiKeF05** [comment] 2022-01-04 10:30
Do you use a ledger for your profile? If yes make sure to connect and sync your profile.

**Comment by YTC329** [comment] 2022-01-04 14:54
> 

Hi Mike,

Yes, I already connected my Ledger, but what do you mean sync my profile? Thanks

**Comment by MiKeF05** [comment] 2022-01-04 15:11
There is a refresh button next to the transaction history. This will sync your profile. Have you tried this?

**Comment by YTC329** [comment] 2022-01-04 15:20
You mean the refresh button next to the "Latest Transactions"? Just tried it and still can't see hidden wallet (Already clicked show hidden wallet" Thanks

**Comment by MiKeF05** [comment] 2022-01-06 12:39
@YTC329 Have you also tried to restore your profile?

**Comment by YTC329** [comment] 2022-01-06 14:54
Hi Mike, do you mean I delete my profile and re-enter my Ledger seed to restore it?

**Comment by MiKeF05** [comment] 2022-01-06 15:02
You don't need to delete your profile to test it. You can directly create a new profile and restore your profile using the ledger device.

**Comment by YTC329** [comment] 2022-01-06 15:15
Hi Mike, just tested it. My "hidden Wallet 3" still has not shown up. Also I feel the refreshing circle icon is spinning forever, thanks

**Comment by YTC329** [comment] 2022-01-06 15:32
Wallet 3 was hidden but there is 0 balance. Yeah, the device displays "generating address"

**Comment by YTC329** [comment] 2022-01-06 15:41
Wait, I think it is working now. I can generate "Wallet 3" in the new restored profile, and when I go back to check my old profile, I can see it now if I click show hidden wallet.
I think the bug is if there is no balance in a hidden wallet from the old file, I could not unhidden it, but if there is balance inside, I can see it. Thanks

**Comment by nicole-obrien** [comment] 2022-01-06 15:52
Duplicate of #1477

**Closed by nicole-obrien** 2022-01-06 15:52 UTC
Labels: type:bug, status:duplicate

**Comment by MiKeF05** [comment] 2022-01-06 17:23
@YTC329 Okay great to hear. So I think you can choose to use one profile now. If you go to C:\Users\ [user]\AppData\Roaming\Firefly\__storage__ you are able to delete the profile you don´t need anymore.
