### ISSUE TITLE
[Bug report]: ENOENT, public/build/index.node not found

### ISSUE THREAD

**Issue by kleyba** [iotaledger/firefly#2965] opened 2022-04-19 18:34 UTC
### Platform

Desktop

### Version

1.5

### Description

open the app I get the following error

App Version: 1.5.0

platform: linux
platformVersion: 5.4.0-107-generic
platformArchitecture: x64
cpuCount: 4
totalMem: 15705.2 MB
freeMem: 1782.4 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: ENOENT, public/build/index.node not found in /tmp/.mount_fireflQETEJ8/resources/app.asar

### Expected behaviour

the program to open

### Actual behaviour

get error message

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

First I did the update with the software update command but got the error
Then I deleted and redownloaded and got the same error. 

### Operating System

Linux

### Diagnostics

```shell
does not do anything
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

White screen

### Error Messages

App Version: 1.5.0

platform: linux
platformVersion: 5.4.0-107-generic
platformArchitecture: x64
cpuCount: 4
totalMem: 15705.2 MB
freeMem: 1782.4 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: ENOENT, public/build/index.node not found in /tmp/.mount_fireflQETEJ8/resources/app.asar

### Error Logs

```shell
none
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment] 2022-04-19 19:00
Did you update using the auto-updater? And can you check the SHA-256 hash of the AppImage against the one posted in the release notes?

**Comment by kleyba** [comment] 2022-04-19 21:03
yes first with the auto-updater then I downloaded from the site.
I'll check the hash.

**Comment by rajivshah3** [comment] 2022-04-19 21:49
This looks like a duplicate of #2766 . I'm still not sure of the cause though

**Closed by rajivshah3** 2022-04-19 21:49 UTC
Labels: bug report

**Comment by kleyba** [comment] 2022-04-20 00:01
does seem to be the same error i did check the hash is good also checked the signature also good.
