### ISSUE TITLE
could help me?

### ISSUE THREAD

**Issue by sertrick8** [iotaledger/firefly#1103] opened 2021-05-02 14:43 UTC
App Version: 1.1.0
I don´t know why I see it in my computer and I can't use firefly.

platform: macOS
platformVersion: 11
platformArchitecture: x64
cpuCount: 8
totalMem: 8192.0 MB
freeMem: 29.3 MB
userPath: /Users/sergioalvarezguzman/Library/Application Support/Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at /Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:165586
    at /Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (/Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197594)
    at /Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:191379

**Comment by cvarley100** [comment] 2021-05-05 19:42
Duplicate of #1087

**Closed by cvarley100** 2021-05-05 19:42 UTC
Labels: bug
