### ISSUE TITLE
On initial onboarding "Receive" and "Send" stays non-translated until restart of app

### ISSUE THREAD

**Issue by t00k** [iotaledger/firefly#925] opened 2021-04-19 09:44 UTC
## Issue description

When first downloading and doing the onboarding for Firefly wallet the "Receive" and "Send" button beneath Balance stays non-translated, while everything else is in the right language. This is fixed by a restart of the app.

## Wallet version

FF 0.4.0

## Steps To reproduce the issue

1. Download Firefly fresh without earlier accounts.
2. Start onboarding procedure and change language.
3. Go through with onboarding.

## Expected behaviour

Everything should be translated, including Receive and Send.

## Actual behaviour

Receive and Send stays non-translated until restart of app.

After onboarding, before restart.
<img width="610" alt="Schermafbeelding_2021-04-19_om_11 31 51" src="https://user-images.githubusercontent.com/49842330/115216150-851acf80-a104-11eb-95dc-a45ba67d1a66.png">

After restart of Firefly.
<img width="368" alt="Schermafbeelding_2021-04-19_om_11 35 02" src="https://user-images.githubusercontent.com/49842330/115216225-9532af00-a104-11eb-9f43-0b00e8487cfe.png">

**Comment by obany** [comment] 2021-04-19 09:49
Duplicate of https://github.com/iotaledger/firefly/issues/890 I don't think was merged into the migration branch on last build - I will double check it is fixed

**Closed** 2021-04-20 08:20 UTC
Labels: bug
