### ISSUE TITLE
Firefly Beta not starting properly on Win10

### ISSUE THREAD

**Issue by s4lt32** [iotaledger/firefly#641] opened 2021-03-22 18:41 UTC
## Issue description
I installed Firefly Beta 0.3.0 for Windows (downloaded from the Beta-Release Blogpost Link), however the app only opens as a white window, no frame, no close button, no anything.

## Wallet version

0.3.0 Windows

- wallet version (version number, commit, or branch):

## System specification
Win10, latest updates as of 22.03.2021.
8GB RAM, Intel i5 4200U, Intel HD Graphcs

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

1. Install Firefly. 
2. Start the exe. 
3. Result: White window

## Expected behaviour

The wallet app starting up.

## Actual behaviour

White screen.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.
![grafik](https://user-images.githubusercontent.com/81186335/112041382-a230a280-8b46-11eb-9233-ce43dc2295fa.png)

**Comment by s4lt32** [comment] 2021-03-22 18:49
![grafik](https://user-images.githubusercontent.com/81186335/112042336-b032f300-8b47-11eb-91d5-f01e0823dccf.png)

**Comment by s4lt32** [comment] 2021-03-22 18:55
Win10 Build 19042

**Comment by nusi506** [comment] 2021-03-22 20:32
same Problem with Win10 Build 19042

**Comment by ivan82itg** [comment] 2021-03-23 10:09
same problem with Win10 Build 19041.867
<img width="960" alt="Captura de pantalla 2021-03-22 232004" src="https://user-images.githubusercontent.com/81229381/112130005-4575cc00-8bc8-11eb-8fa6-48872772329e.png">

**Comment by Tayotakid** [comment] 2021-03-23 10:32
same problem on firefly 0.3.1 build 19042.867 (windows 10)

**Comment by Tinchen123** [comment] 2021-03-24 08:52
same problem (Windows 10)

**Comment by svenger87** [comment] 2021-03-25 06:54
Duplicate of #465

**Comment by svenger87** [comment] 2021-03-25 07:00
I have an idea what could be the issue. Do you all have Intel HD graphics?
Does anyone have a Notebook with Nvidia Optimus? (Separate dedicated GPU).

Could you run FireFly with the dedicated GPU? Right click FireFly.exe and run with dedicated Nvidia GPU.

**Comment by Tayotakid** [comment] 2021-03-25 13:02
Yes Intel hd graphics with no dedicated gpu for me, xps 13 2014

**Comment by Tinchen123** [comment] 2021-03-25 17:35
Yes, also Intel (R) HD-Graphics

**Comment by svenger87** [comment] 2021-03-25 17:48
@rajivshah3 fyi

**Comment by rajivshah3** [comment] 2021-03-25 18:21
Does starting Firefly with the `--disable-gpu` flag help?

**Comment by Tayotakid** [comment] 2021-03-27 09:40
> Does starting Firefly with the `--disable-gpu` flag help?

How do we do that plz ?

**Comment by svenger87** [comment] 2021-03-27 10:43
> > Does starting Firefly with the `--disable-gpu` flag help?
> 
> How do we do that plz ?

Right click the desktop shortcut and add the parameter with a leading space to the destination.

**Comment by Tayotakid** [comment] 2021-03-27 11:11
Is that correct ? didn't work 
![Sans titre](https://user-images.githubusercontent.com/81187221/112718799-9867c000-8ef5-11eb-9cdc-1be6340880f7.png)

**Comment by svenger87** [comment] 2021-03-27 12:34
> Is that correct ? didn't work
> ![Sans titre](https://user-images.githubusercontent.com/81187221/112718799-9867c000-8ef5-11eb-9cdc-1be6340880f7.png)

Yes it's correct. But the parameter didn't work for me too.

**Comment by obany** [comment] 2021-03-29 08:47
Could you try installing the VC++ runtime and see if this fixes the issue https://www.microsoft.com/en-us/download/details.aspx?id=53840

**Comment by Tayotakid** [comment] 2021-03-29 14:32
It worked ! thanks !

**Comment by Tinchen123** [comment] 2021-03-29 16:56
"Could you try installing the VC++ runtime and see if this fixes the issue"

Yes, it works :-) Thank you :-)

**Comment by s4lt32** [comment] 2021-03-29 18:37
Yes, white window issue also fixed for me now. Thanks!

**Closed** 2021-03-30 06:43 UTC
Labels: P - Windows, bug
