### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by mogulbuster** [iotaledger/firefly#7348] opened 2023-08-22 17:55 UTC
### Platform

Desktop

### Version

1.7.3

### Description

App Version: 1.7.3

platform: macOS
platformVersion: 10.15.7
platformArchitecture: x64
cpuCount: 4
totalMem: 24576.0 MB
freeMem: 4768.6 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

### Expected behaviour

Normal selection of different acounts

### Actual behaviour

Error message

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

Non-responsive

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment] 2023-08-23 08:06
Duplicate of https://github.com/iotaledger/firefly/issues/7324

**Closed by begonaalvarezd** 2023-08-23 08:06 UTC
Labels: bug report

**Comment by begonaalvarezd** [comment] 2023-08-29 13:26
Hi, we just released the new version 1.7.4 which contains the fix

### Firefly IOTA 1.7.4 announcement message

We just released Firefly IOTA 1.7.4. Among the changes, it contains the fixes for macOS crash at startup and the slow stronghold export. 

:warning: Important: macOS 10.13 will not be supported anymore in Firefly IOTA, so if you are running macOS 10.13 we highly recommend upgrading your macOS version to a newer one. 

:pencil: Changelog:

- fix slow stronghold export
- fix macOS support (official drop support macOS <= 10.13)
- add official asmb staking event 6 results

:arrow_down:  Download:
https://firefly.iota.org/

:bug:  Bug Reporting:
https://github.com/iotaledger/firefly/issues/new?assignees=&labels=bug+report&template=bug_report.yml&title=%5BBug+report%5D%3A
