### ISSUE TITLE
Error message when opening firefly desktop app PC

### ISSUE THREAD

**Issue by hkyaumati** [iotaledger/firefly#1179] opened 2021-05-31 06:36 UTC
App Version: 1.1.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 8
totalMem: 16339.4 MB
freeMem: 11708.2 MB
userPath: C:\Users\Xxxx\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at C:\Users\Xxxx\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:165586
    at C:\Users\Xxxx\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\Xxxx\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197594)
    at C:\Users\Xxxx\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:191379

Please help.

**Comment by nicole-obrien** [comment] 2022-01-06 15:36
Duplicate of #1087

**Closed by nicole-obrien** 2022-01-06 15:36 UTC
Labels: type:bug, status:duplicate
