### ISSUE TITLE
Error with Firefly, the network doesn't work

### ISSUE THREAD

**Issue by jerhubgitjul** [iotaledger/firefly#1660] opened 2021-11-27 14:07 UTC
### Issue description

Hi,

In my Firefly, my wallet isn't showing, my crypto is not there either.

Please, can i have confirmation that this will be resolved as soon as possible.

Best Regards,

M.Theytaz

### Firefly version

Firefly v1.2.0

### OS details

Windows 10 Professionnel, 20H2, Build 19042.1348

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Install Firefly
2. Connect to your profile/wallet
3. Note that no wallet can be displayed, because the network is disconnected.

### Expected behaviour

I expected to see my wallet and IOTA balance, none of this is showing.

### Actual behaviour

I cannot access my wallet on Firefly, it has been going on for several days. I am very annoyed by this problem, I cannot access my IOTA.

### Errors

![IOTA error picture](https://user-images.githubusercontent.com/90267559/143684843-bcc9f0cc-bf07-4330-af4b-d4c310fab73c.JPG)

**Comment by MiKeF05** [comment] 2021-11-27 14:24
Yes this is a known bug and will hopefully be fixed with the new version of Firefly. In the meantime you can try to create a new profile and restore your wallet with your ledger device.

**Comment by jerhubgitjul** [comment] 2021-11-29 22:03
Yes I changed my password before this error, but I'm sur that's right, when I'm connected in Firefly, I see the name of my wallet, but there is no wallet and no funds, I don't see my IOTA.The network Firefly is disconnected.Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : nicole-obrien ***@***.***> Date : 29.11.21  16:25  (GMT+01:00) À : iotaledger/firefly ***@***.***> Cc : jerhubgitjul ***@***.***>, Mention ***@***.***> Objet : Re: [iotaledger/firefly] Error with Firefly, the network doesn't work (Issue #1660) 
@jerhubgitjul did you change you pin or password before this occurred? Or was this on new profile?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iotaledger/firefly/issues/1660#issuecomment-981740118",
"url": "https://github.com/iotaledger/firefly/issues/1660#issuecomment-981740118",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by nicole-obrien** [comment] 2021-11-29 22:10
Thanks this is then a duplicate of: https://github.com/iotaledger/firefly/issues/1656 and we are working on a fix for the next release. I will therefore close this issue so we can track it in one place. You can create a new profile and restore your account from your back up or 24 word mnemonic. If you need support don't forget you can ask in our discord: https://discord.iota.org/

**Closed by nicole-obrien** 2021-11-29 22:10 UTC
Labels: type:bug
