### ISSUE TITLE
Firefly not reaktion after deleting profile

### ISSUE THREAD

**Issue by adertask** [iotaledger/firefly#1522] opened 2021-10-04 08:25 UTC
### Issue description

When I delete successfully a profile Firefly wasn't reakting anymore. 

### Firefly version

1.2.0

### OS details

10.0.19043

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1) Have some profiles
2) Delete one

But also the naming of still existing profiles (icon with first letter of profile name) didn't match.
If you had:
Profile 1: Name 'Wallet 1' - Naem in Icon / circle -> W1
Profile 2: Name 'Wallet 2' - Naem in Icon / circle -> W2
Profile 3: Name 'Wallet X' - Naem in Icon / circle -> WX

Deleting Profile 1 results in naming
Profile 2: Name 'Wallet 2' - Naem in Icon / circle -> W1
Profile 3: Name 'Wallet X' - Naem in Icon / circle -> W2
And as written.. Firefly is frozen now

### Expected behaviour

Firefly should not be "frozen"

### Actual behaviour

Firefly is frozen

### Errors

No logs.

**Comment by nicole-obrien** [comment] 2021-10-05 19:15
Thank you, closing because this is a duplicate of #1054

**Closed** 2021-10-05 19:16 UTC
Labels: bug, duplicate
