### ISSUE TITLE
unable to create a wallet - error message

### ISSUE THREAD

**Issue by mtjbaumann** [iotaledger/firefly#1270] opened 2021-07-19 16:57 UTC
App Version: 1.1.0

platform: macOS
platformVersion: 11
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 226.2 MB
userPath: /Users/tombaumannimac/Library/Application Support/Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at /Users/tombaumannimac/Desktop/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:165586
    at /Users/tombaumannimac/Desktop/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (/Users/tombaumannimac/Desktop/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197594)
    at /Users/tombaumannimac/Desktop/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:191379

**Comment by hristo-mavrodiev** [comment] 2021-07-24 06:51
https://github.com/iotaledger/firefly/issues/1087

**Comment by nicole-obrien** [comment] 2022-01-06 15:35
Duplicate of #1087

**Closed by nicole-obrien** 2022-01-06 15:35 UTC
Labels: type:bug, status:duplicate
