### ISSUE TITLE
Firefly freezes after deleting a profile

### ISSUE THREAD

**Issue by t00k** [iotaledger/firefly#1357] opened 2021-08-03 11:31 UTC
## Issue description

Firefly freezes and you are unable to click anything after you deleted a profile and is on the login screen.

## Wallet version

Build #156, Windows 10.

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Login to a profile, go into settings -> delete that profile.

## Expected behaviour

Your profile should be deleted and you should be able to login to another or do whatever.

## Actual behaviour

Firefly completely freezes. Unable to click anything. Need to force-close from task manager.

## Errors

None in the error log or Dev Tools.

**Comment by wonkytonky2** [comment] 2021-08-05 21:41
can confirm for ledger and non ledger profiles

small issue but lets get this fixed :)

**Comment by baylander** [comment] 2021-08-08 10:13
Also can confirm this behavior with Firefly Version1.2.0.
OS: Tested on Win10 (21H1 Build 19043.1110)

**Comment by Tobivaria** [comment] 2021-08-09 15:34
Can confirm firefly freezes after deleting a profile.

Firefly v1.2.0
Plattform: win32
Plattformversion: 10.0.19043
Plattform-Architektur: x64
CPU-Anzahl: 12
Gesamtspeicher: 16288.7 MB
Freier Speicher: 6164.5 MB
Benutzerpfad: C:\Users\tobia\AppData\Roaming\Firefly

**Comment by sulikdan** [comment] 2021-09-18 20:20
Also confirming
Firefly v1.2.0
Win10 PRO (21H1 Build 19043.1237)

**Comment by nicole-obrien** [comment] 2021-10-05 19:15
Thank you, closing because this is a duplicate of #1054

**Closed by nicole-obrien** 2021-10-05 19:15 UTC
Labels: bug, (platform) windows
