### ISSUE TITLE
[Bug]: Unable to access Ledger profile

### ISSUE THREAD

**Issue by Bewater2140** [iotaledger/firefly#2341] opened 2022-02-16 15:59 UTC
### Issue description

I have the app connected to my Ledger wallet and after the latest update 1.3.3 I can't log in. The screen stays on the butterfly fluttering and after a while the screen goes blank, but it does not enter the application.

### Expected behaviour

Help to access my funds

### Actual behaviour

I went into the application to get the shipping address for a transaction, I had to connect the Ledger to validate the address and I sent the coins. Before receiving the funds and without disconnecting the Ledger I started the update process because I saw the notice of the new update available. The application restarted and I could not log in anymore.

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

I don't know how it could be reproduced

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment] 2022-02-16 17:08
Do you use windows?

**Comment by Rooobsch** [comment] 2022-02-16 18:24
Same here .. i created a Profil .. set up my ledger and transfer some MIOTA`s to the seed .. now it won`t open .. it stays on the butterfly and my Pin is correct .. i hope that my IOTA`s aren`t trash .. :(

**Comment by MiKeF05** [comment] 2022-02-16 20:58
Don't worry your tokens are stored on nodes in the network. Firefly is just the GUI to connect to a node.

Can you try to restore your profile? Create a new profile -> recover wallet -> Ledger backup -> Firefly ledger backup.

**Comment by Bewater2140** [comment] 2022-02-16 21:56
Wow!!! thank you very much. it was very simple and everything works correctly. How can I delete the profiles that have stopped working?

**Comment by Rooobsch** [comment] 2022-02-16 21:58
> Don't worry your tokens are stored on nodes in the network. Firefly is just the GUI to connect to a node.
> 
> Can you try to restore your profile? Create a new profile -> recover wallet -> Ledger backup -> Firefly ledger backup.

I`ll try it later .. Hope that it works for me .. like @Bewater2140 down below ..

**Comment by Rooobsch** [comment] 2022-02-16 22:14
> Wow!!! thank you very much. it was very simple and everything works correctly. How can I delete the profiles that have stopped working?

That works for me too .. i have restored my Wallet with a new Profil ..

**Comment by kraftjs** [comment] 2022-02-16 22:31
Seems related to #2343 which I converted from a [discussion](https://github.com/iotaledger/firefly/discussions/2338), but they were able to begin staking before Firefly froze on them. I am able to reproduce this bug with a new Firefly Ledger profile.

1) Create a profile with Ledger
2) Generate address with Ledger
3) Send to address
4) Firefly freezes and funds aren't updated
5) Opening Firefly again and accessing Ledger profile never passes loading screen (but accessing non-ledger profiles still works)

**Comment by MiKeF05** [comment] 2022-02-16 22:41
@Bewater2140 
In the next release of Firefly you will also be able to delete profiles with balances. In the meantime you can go to `C:\Users\[username]\AppData\Roaming\Firefly\__storage__`. There you can delete the profile you want to delete.

**Comment by Rooobsch** [comment] 2022-02-16 23:04
> @Bewater2140 In the next release of Firefly you will also be able to delete profiles with balances. In the meantime you can go to `C:\Users\[username]\AppData\Roaming\Firefly\__storage__`. There you can delete the profile you want to delete.

Perfect. Just deleted it and the restored Profil works as it should. Thx!

**Comment by Bewater2140** [comment] 2022-02-16 23:28
> @Bewater2140 In the next release of Firefly you will also be able to delete profiles with balances. In the meantime you can go to `C:\Users\[username]\AppData\Roaming\Firefly\__storage__`. There you can delete the profile you want to delete.

Everything solved and working correctly.
Thank you very much for the quick and efficient response. I congratulate you for the work you do, keep up the good work!
And by the way, I find the staking system a bit strange, when you delegate new coins, first you get back all the staked and then send all the coins again, wouldn't it be easier to simply add the coins to the staking, as the other protocols do?

**Comment by kraftjs** [comment] 2022-02-17 16:48
Closing this because I created issue #2345 that encompasses this bug and similar ones.

**Closed by kraftjs** 2022-02-17 16:48 UTC
Labels: type:bug, priority:2
