### ISSUE TITLE
Automatically login with out clicking continue

### ISSUE THREAD

**Issue by chip77z** [iotaledger/firefly#747] opened 2021-03-25 20:11 UTC
## Description

Upon entering your 6 digit passcode, the application automatically logs in, without the user needing to click continue. 

## Motivation

improve user experience

## Requirements

Write a list of what you want this feature to do.

1. Upon successfully entering the correct pin code, the application automatically logs in
2. Where entering an incorrect pin code, an error message is displayed
3. Remove the continue button

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No

**Comment by obany** [comment] 2021-03-26 07:12
Duplicate of https://github.com/iotaledger/firefly/issues/332

**Closed by obany** 2021-03-26 07:12 UTC
Labels: enhancement
