### ISSUE TITLE
[Task]: E12.M3 - Peripheral action - set nft as profile avatar

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3454] opened 2022-06-10 17:39 UTC
### Task description

TBD

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by kraftjs** [comment] 2022-12-23 18:26
Dupe of #5510

**Closed by kraftjs** 2022-12-23 18:26 UTC
Labels: stardust, context:collectibles
