### ISSUE TITLE
Firefly issue

### ISSUE THREAD

**Issue by BTschorn** [iotaledger/firefly#1673] opened 2021-12-01 09:02 UTC
### Issue description

App Version: 1.2.0

platform: win32

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

### Firefly version

1.2.0

### OS details

win32

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

no idea what happened.
firefly was open long time

### Expected behaviour

nothing

### Actual behaviour

PC in standby

**Comment by JamesonB** [comment] 2021-12-09 16:12
I also see this, but on Mac:

App Version: 1.2.0

platform: macOS
platformVersion: 10.13
platformArchitecture: x64
cpuCount: 4
totalMem: 16384.0 MB
freeMem: 742.5 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

**Comment by smieg** [comment] 2021-12-11 20:16
Same message today - wallet was left open for a while


App Version: 1.2.0

platform: macOS
platformVersion: 10.15
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 192.9 MB
userPath: /Users/S...............Library/Application Support/Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

**Comment by perandre** [comment] 2021-12-27 09:29
Duplicate of https://github.com/iotaledger/firefly/issues/1127

**Comment by MiKeF05** [comment] 2022-01-05 23:37
@BTschorn @JamesonB @smieg After the error appeared were you able to use Firefly normally after a restart?

**Comment by MiKeF05** [comment] 2022-01-14 20:30
Duplicate to #2123

**Closed** 2022-01-14 20:31 UTC
Labels: type:bug
