### ISSUE TITLE
Firefly portfolio graph history incorrect 

### ISSUE THREAD

**Issue by LifelikeBug** [iotaledger/firefly#1391] opened 2021-08-09 18:17 UTC
## Issue description

When I was testing the firefly wallet out after a transaction to one of my wallets my portfolio graph history was set to zero even though I had iotas in my wallet in the past.

## Wallet version

Which version of wallet are you using?

- wallet version 1.2.0

## System specification

What is your operating system?

window 10 pro

## Is it a repeatable issue?

No. I think I would have to have the ability to delete a wallet to repeat.

## Steps To reproduce the issue

Only did this once so here is what I did

1. Only have one wallet in the firefly account. Having hidden wallets or more than one makes the bug impossible to replicate from my tests.
2. have iota on the one wallet. 
3. make a wallet I named mine fun
4. click on the new wallet and then click the copy address
5. then go to the oldest wallet and click send funds
6. I used the send payment and pasted the copied address. Then click send. I did 1 Mi.
7. After this the bug happened

## Expected behaviour

After this, the portfolio graph history is set to zero and the bug should be impossible to replicate after this.

## Actual behaviour

now after doing it on my first try I can not do it anymore.

## Errors

no Error codes

**Comment by begonaalvarezd** [comment] 2021-08-10 13:55
@LifelikeBug Can you please attach a screenshot about the situation? I tried replicating your issue but I can't 🙏🏼

**Comment by LifelikeBug** [comment] 2021-08-10 19:19
I really tried to replicate this myself but can't. Maybe it has to do with the fact that the iotas in my account were there from the migration instead of from me sending it from a different account wallet. I have had the same amount of iotas since the chrysalis was first available. 
![image](https://user-images.githubusercontent.com/72219078/128921589-17abaefc-9c63-4df1-9cab-9411363fd061.png)

**Comment by LifelikeBug** [comment] 2021-08-10 19:39
probably not worth fixing TBH

**Comment by begonaalvarezd** [comment] 2021-08-11 07:42
I see. The graph is plotted using a combination of your current balance and the message history. If there is no history before message X, we just set it to zero (the other way is taking your last known balance and just plot a straight like back in time, but that might also not be correct). This is a known issue we "patched" this way to minimize impact.

**Comment by mohammad592002** [comment] 2021-08-11 20:45
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qq0tkn6t4u0kvw9urddt8ap6pjyfcynnncslry5w49em745alplmg8qgavj/outputs?include-spent=true): operation timed out`

**Comment by cvarley100** [comment] 2021-09-06 17:04
Duplicate of #864

**Closed by cvarley100** 2021-09-06 17:04 UTC
Labels: bug
