### ISSUE TITLE
wallet does not work. There is just a blank window!

### ISSUE THREAD

**Issue by zinn711** [iotaledger/firefly#1047] opened 2021-04-28 14:54 UTC
## Issue description

Briefly describe the issue.

## Wallet version
1.0.0

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?
Mac OS 10.11.6

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. install the wallet
2. open the wallet
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by kmlnts** [comment] 2021-04-28 16:05
It is not possible to download wallet for Linux (empty page)

**Comment by cgaluppo** [comment] 2021-04-28 17:18
I'm having the same problem. Once I've instaled, when I insert the seed frase from Trinity wallet, it open a blank page and after that I can't do anything else.

**Comment by mucahitaltntas** [comment] 2021-04-28 18:51
The same problem occurred with me, I entered the codes and a blank page appeared in front of me.

**Comment by mucahitaltntas** [comment] 2021-04-28 18:53
![Screenshot_679](https://user-images.githubusercontent.com/60298396/116457518-2a077c00-a86c-11eb-87ff-d8c1ba224af8.jpg)

**Comment by mucahitaltntas** [comment] 2021-04-28 18:54
> Aynı sorun bende de oldu, kodları girdim ve önümde boş bir sayfa belirdi.

![Screenshot_679](https://user-images.githubusercontent.com/60298396/116457602-46a3b400-a86c-11eb-8436-0174b5ac7190.jpg)

**Comment by kmueller** [comment] 2021-04-28 21:07
See https://github.com/iotaledger/firefly/issues/897

**Comment by Malt1985** [comment] 2021-04-29 20:24
Same here on my (Windows 10) laptop

**Comment by eKing021** [comment] 2021-04-30 03:58
same
Mac 10.13.6
Firefly 1.0.0

**Comment by rajivshah3** [comment] 2021-04-30 23:20
Hi, there's a few different issues going on here. 

- @eKing021 this issue should be fixed with the latest release which now supports macOS Sierra and later
- @zinn711 you'll need to update to at least macOS Sierra (10.12) in order for Firefly to work
- @Malt1985 @mucahitaltntas @cgaluppo @kmlnts please check if the issue is resolved in the latest version. If not, please open a separate issue so we can track it easily

I'll close this as the original issue should be resolved now

**Closed by rajivshah3** 2021-04-30 23:20 UTC
Labels: bug
