### ISSUE TITLE
Warning: funds at risk during migration

### ISSUE THREAD

**Issue by pekar007** [iotaledger/firefly#1106] opened 2021-05-02 19:43 UTC
## Issue description

Warning: funds at risk during migration

## Wallet version

IOTA Light Wallet 2.5.7 -IRI 0.5.6

- wallet version (version number, commit, or branch):

## System specification

Windows 10

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. 
2.
3.

## Expected behaviour

Describe what you expect to happen.
[Issue during IOTA migration.docx](https://github.com/iotaledger/firefly/files/6412123/Issue.during.IOTA.migration.docx)

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Phyloiota** [comment] 2021-05-02 23:57
Hey. Please continue the migration.
Firefly will start a procces that will limit the risk of mirating the funds at spent addresses.
The problem is that funds on spent addresses had already a part of the private key of that address reveald due to the nature of the WOTS one time signature sheme.
Firefly will start a proccess called bundle mining and search for the best way to reveal as less possible of your key during the migration (which would be an attack vector).
This proccess will be a high cryptographic task and take 10 minutes per spent address per bundle mining proccess. You rcpus will run on 100% during this time. Afterwards wou will presented with a risk estimation (how good the proccess hides the keys now)
It is possible that you need to run this mining proccess several time untill you reach at least medium risk level and then you can procceed the normal migration.
So plan some time - depends on the ammount of spent addresses and how complicated the case is this could take several hours.
But Firefly will do the best poosible solution to move those funds

**Comment by rajivshah3** [comment] 2021-05-03 16:27
Closing as this is not a bug

**Closed by rajivshah3** 2021-05-03 16:27 UTC
Labels: bug

**Comment by mohammad592002** [comment] 2021-08-11 20:42
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qq0tkn6t4u0kvw9urddt8ap6pjyfcynnncslry5w49em745alplmg8qgavj/outputs?include-spent=true): operation timed out`
