### ISSUE TITLE
[Bug report]: Deep links on linux

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3818] opened 2022-07-06 13:23 UTC
### Platform

Desktop

### Version

stardust-develop

### Description

Deep links in linux fail when a user is not logged in.

Potentially related issue: https://github.com/iotaledger/wallet.rs/issues/1245

### Expected behaviour

Clicking a deep link should open Firefly on the select profile page with a notification that a login is required for handling the deep link.

### Actual behaviour

Clicking a deep link opens a new instance of Firefly, with no additional behavior. Upon logging in, the deep link is not handled.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Ensure Firefly is closed
2. Click on a deep link (e.g.: [firefly-alpha://wallet/sendForm?address=rms1qrut5ajyfrtgjs325kd9chwfwyyy2z3fewy4vgy0vvdtf2pr8prg5u3zwjn&amount=100&metadata=helloworld&tag=firefly](firefly-alpha://wallet/sendForm?address=rms1qrut5ajyfrtgjs325kd9chwfwyyy2z3fewy4vgy0vvdtf2pr8prg5u3zwjn&amount=100&metadata=helloworld&tag=firefly))
3. Firefly opens the select profile page without notification

### Operating System

Linux

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marc2332** [comment] 2023-10-11 07:01
Duplicate of https://github.com/iotaledger/firefly/issues/3818

**Closed by marc2332** 2023-10-11 07:01 UTC
Labels: bug report
