### ISSUE TITLE
FATAL:gpu_data_manager_impl_private.

### ISSUE THREAD

**Issue by StefanoD** [iotaledger/firefly#1628] opened 2021-11-09 18:36 UTC
### Issue description

Hi,
I upgraded from Fedora 34 to 35 and since this latest version, I enabled Wayland (I had to do this manually, because I have an NVIDIA graphics card, where the support is somewhat experimental).
Since then I can't start Firefly anymore, because it crashes immediately.

### Firefly version

1.2.0

### OS details

Feora 35 (Wayland)

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

Just start the app

### Expected behaviour

The app should start

### Actual behaviour

The app crashes

### Errors

```
(base) [stefano@localhost Apps]$ ./firefly-desktop-1.2.0.AppImage 
19:30:37.998 › Checking for update
19:30:38.483 › Update for version 1.2.0 is not available (latest version: 1.2.0, downgrade is disallowed).
[7558:1109/193039.256146:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

**Comment by rajivshah3** [comment] 2021-11-21 18:24
Hi, can you try starting Firefly with the `--disable-gpu` flag?

**Comment by StefanoD** [comment] 2021-11-21 19:39
Still doesn't work:
`
$ ./firefly-desktop-1.2.0.AppImage --disable-gpu
20:38:21.812 › Checking for update
20:38:22.603 › Update for version 1.2.0 is not available (latest version: 1.2.0, downgrade is disallowed).
[27960:1121/203822.864467:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
(node:28031) Electron: Loading non-context-aware native module in renderer: '/tmp/.org.chromium.Chromium.ByD4S7'. This is deprecated, see https://github.com/electron/electron/issues/18397.
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
`

**Comment by StefanoD** [comment] 2021-11-21 19:41
Ok, with `--ignore-gpu-blacklist` everything works! :)

**Comment by rajivshah3** [comment] 2021-11-21 19:42
Great! Would you be able to send a screenshot of the "Graphics Feature Status" section from `chrome://gpu/` if you have Google Chrome installed?

**Comment by StefanoD** [comment] 2021-11-21 19:43
[gpu_info.txt](https://github.com/iotaledger/firefly/files/7576956/gpu_info.txt)

**Comment by rajivshah3** [comment] 2021-11-21 19:57
Thanks! Do you happen to use Discord or other Electron apps with hardware acceleration disabled?

**Comment by StefanoD** [comment] 2021-11-21 19:59
I just use the default settings. I don't modify any settings on purpose.

**Comment by rajivshah3** [comment] 2021-11-21 20:37
Ok. After some research it looks like this was resolved in later versions of Electron, so it may take us a little while to resolve this issue. The `--ignore-gpu-blacklist` flag may be necessary for a little bit

**Comment by StefanoD** [comment] 2021-12-22 12:10
For some reasons even --ignore-gpu-blacklist doesn't work anymore for version 1.2.0 and 1.3.0.

**Comment by rajivshah3** [comment] 2021-12-28 18:59
@StefanoD someone reported that `--disable-gpu-sandbox` works. Can you try that?

**Comment by StefanoD** [comment] 2021-12-28 19:47
@rajivshah3 Yes, this works.

**Comment by rajivshah3** [comment] 2022-01-05 17:14
Just adding some notes:

@viossat is also able to reproduce this issue and we're able to detect the killing of the GPU process by handling the [`child-process-gone` event](https://www.electronjs.org/docs/v14-x-y/api/app#event-child-process-gone). I'm wondering if we can detect this event and automatically relaunch Firefly with hardware acceleration disabled, as that might work around the issue in the meantime until we update Electron

**Comment by loeweh** [comment] 2022-03-27 16:37
Hi, tried out the latest version 1.3.3. it still crashes. Any timeline a fix?

**Comment by ServiceDog** [comment] 2022-04-29 17:04
Seconded, `--disable-gpu-sandbox` works, otherwise getting the error:
```bash
09:58:25.621 › Checking for update
09:58:25.798 › Update for version 1.5.1 is not available (latest version: 1.5.1, downgrade is disallowed).
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[22587:0429/095826.751321:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

**Comment by h0lley** [comment] 2022-05-03 14:42
Neither of `--ignore-gpu-sandbox` `--ignore-gpu-blacklist` `--disable-gpu` works for me.
Sometimes the application does not crash, but then the window is just white.

```
./firefly-desktop-1.5.1.AppImage
16:40:11.481 › Checking for update
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
16:40:12.275 › Update for version 1.5.1 is not available (latest version: 1.5.1, downgrade is disallowed).
[19417:0503/164012.591971:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

I am not having any issues with applications like Discord or Vivaldi on this system.

```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-27-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 15,6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 970/PCIe/SSE2
```

**Comment by tonygustafsson** [comment] 2022-11-22 06:04
For me it worked with `--no-sandbox` in version 1.7.0.

**Comment by begonaalvarezd** [comment] 2023-08-23 16:49
Closing issue due to inactivity, please upgrade to the latest app version and reopen the issue if the problem persists 🌷

**Closed by begonaalvarezd** 2023-08-23 16:49 UTC
Labels: bug report
