### ISSUE TITLE
Internal Transfer Notification incorrect account display

### ISSUE THREAD

**Issue by AdamCroply** [iotaledger/firefly#737] opened 2021-03-25 11:53 UTC
When transferring between two internal accounts the notification displays the sender and the receiver the wrong way round.

Firefly Beta v0.3.1

Windows 10 Home v20H2

A repeating issue

Explain how the maintainer can reproduce the issue.

1.Select internal transfer
2.Select an account to transfer to
3.Send, and wait for the pop-up notification

Sending and receiving account should be displayed in the notification correctly

What actually happens is the sending and receiving accounts are displayed in the notification the wrong way round
![firefly_screenshot](https://user-images.githubusercontent.com/61834907/112468849-1054af80-8d69-11eb-87a6-e050cfac4517.png)

**Comment by obany** [comment] 2021-03-25 11:55
Duplicate of https://github.com/iotaledger/firefly/issues/624

**Closed by obany** 2021-03-25 11:55 UTC
Labels: bug
