### ISSUE TITLE
Received error message now wallet is empty

### ISSUE THREAD

**Issue by bear2234** [iotaledger/firefly#1159] opened 2021-05-18 22:18 UTC
App Version: 1.1.0

platform: macOS
platformVersion: 10.15
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 1324.3 MB
userPath: /Users/joshuakemper/Library/Application Support/Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at /private/var/folders/0_/xznz2fwd4ns3s4bptt83_7540000gn/T/AppTranslocation/56FB7A0E-8D2A-4D95-AF88-03F58CA57023/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:165586
    at /private/var/folders/0_/xznz2fwd4ns3s4bptt83_7540000gn/T/AppTranslocation/56FB7A0E-8D2A-4D95-AF88-03F58CA57023/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (/private/var/folders/0_/xznz2fwd4ns3s4bptt83_7540000gn/T/AppTranslocation/56FB7A0E-8D2A-4D95-AF88-03F58CA57023/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197594)
    at /private/var/folders/0_/xznz2fwd4ns3s4bptt83_7540000gn/T/AppTranslocation/56FB7A0E-8D2A-4D95-AF88-03F58CA57023/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:191379
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.Changed my login pin right before this happened
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by rajivshah3** [comment] 2021-05-25 18:05
Hi, can you try deleting your account and importing your seed again?

**Comment by nicole-obrien** [comment] 2022-01-06 15:37
Duplicate of #1087

**Closed by nicole-obrien** 2022-01-06 15:37 UTC
Labels: type:bug, status:duplicate
