### ISSUE TITLE
After Firefly update error, can't migrate stronghold 

### ISSUE THREAD

**Issue by controllerpartner** [iotaledger/firefly#7333] opened 2023-08-19 10:05 UTC
### Platform

Desktop

### Version

1.7.3

### Description

After Firefly update error, can't migrate stronghold
My IOS: macOS Big Sur 11.5

Is the migration of stronghold the problem? how to do it, I am not an expert, not able to programming. Is there a tool existing?
there are codelines on wiki.iota.org, but how to use that?

### Expected behaviour

See my holdings

### Actual behaviour

white screen

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac, iOS

### Diagnostics

```shell
App Version: 1.7.3

platform: macOS
platformVersion: 11.5
platformArchitecture: x64
cpuCount: 4
totalMem: 16384.0 MB
freeMem: 571.6 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

White screen

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gerap93** [comment] 2023-08-19 10:13
I have the same issue:

App Version: 1.7.3

platform: macOS
platformVersion: 11.7.8
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 4549.7 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

**Comment by begonaalvarezd** [comment] 2023-08-19 15:03
Hi, we apologize for the trouble, we are working on a fix and will release a new version soon 🙏🏼 
Closing this issue as its a duplicate of https://github.com/iotaledger/firefly/issues/7324

**Closed by begonaalvarezd** 2023-08-19 15:03 UTC
Labels: bug report
