### ISSUE TITLE
Staking not detected 

### ISSUE THREAD

**Issue by Kavir10260** [iotaledger/firefly#1896] opened 2021-12-26 20:29 UTC
### Issue description

ClientError: `Response error with status code 503: {"error":{"code":"503","message":"Service Unavailable, error: node is not synced: code=503, message=Service Unavailable"}}

### Firefly version

1.3.10

### OS details

Windows 11 Pro Education 21996.1

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

I couldn't staking iota

### Actual behaviour

A concise description of what you're experiencing.

### Errors

Sun, 26 Dec 2021 20:22:28 GMT
ClientError: `Response error with status code 502: Bad Gateway`

Sun, 26 Dec 2021 20:15:35 GMT
ClientError: `Response error with status code 404: {"error":{"code":"404","message":"Not Found, error: event not found: 57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb: code=404, message=Not Found"}}
`

Sun, 26 Dec 2021 20:14:48 GMT
ClientError: `Response error with status code 503: {"error":{"code":"503","message":"Service Unavailable, error: node is not synced: code=503, message=Service Unavailable"}}
`

**Comment by r-c-k** [comment] 2021-12-26 20:30
Duplicate #1894

**Comment by Olatuyitony347** [comment] 2021-12-28 11:48
same issue here aswell

**Comment by michaelwants** [comment] 2021-12-29 08:28
👋 Hi, I’m @michaelwants, I am also currently experiencing this problem. I see it has been marked as a bug, does anyone know if there is a solution yet?

Cheers, 

- 👀 I’m interested in ...
- 🌱 I’m currently learning ...

**Comment by khanmac23** [comment] 2021-12-29 08:46
iam having same problem
says status not connected

**Comment by Loki2k3** [comment] 2021-12-29 09:05
same...
waiting for fixing...

**Comment by AlexKunze83** [comment] 2021-12-29 09:39
I have the same problem.

**Comment by GameSoftInteractive** [comment] 2021-12-29 10:07
Same for me. Steps as follows (Windows 10 Professional):
1- Installed Firefly yesterday.
2- Sent MIOTA to Firefly.
3- Staked in both projects. Live staking updates working fine.
4- Started PC this morning, upon Firefly launch "Something went wrong" error message.
5- Clicked on Staking icon, Staked Funds = 0 Mi.

**Comment by r-c-k** [comment] 2021-12-29 10:08
Official statement:

_We have some issues with the COO Node atm, the devs are working already on it, please be patient, you can't do anything at the moment. 
Your Firefly will show "network disconnected" and you don't see your staking rewards. This is just temporary.
At the moment, no new staking rewards are generated during this downtime and no transactions can be issued. Your currently already gained rewards will NOT be lost, the minutes of this downtime will automatically be added to the staking period, so the exact 90 days staking will be achieved._

**Comment by michaelwants** [comment] 2021-12-29 10:31
Thank you ✌️

**Comment by nicole-obrien** [comment] 2021-12-29 10:40
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476130331812106244?s=20

**Closed by nicole-obrien** 2021-12-29 10:40 UTC
Labels: type:bug, status:invalid
