### ISSUE TITLE
Firefly stuck after setup from stronghold when waiting too long

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#839] opened 2021-04-10 18:30 UTC
## Issue description

If too much time passes (~2 minutes) before verifying the newly created pin-code after loading a stronghold backup in the profile creation process, the application shows an error message "Something went wrong." and gets stuck.

## Wallet version

v0.4.0

## System specification

macOS 11.3 Beta

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

1. While onboarding, load a stronghold backup
2. Before verifying the newly created pin-code to finish the setup, wait approximately 2 minutes
3. Continue to finish setup

## Expected behaviour

The profile/wallet setup should finish and profile should be opened 

## Actual behaviour

Stuck with an error message saying "Something went wrong."

## Errors

<img width="1744" alt="Bildschirmfoto 2021-04-10 um 20 21 05" src="https://user-images.githubusercontent.com/17240275/114280828-72850400-9a3b-11eb-8abf-9186f88d93e8.png">
<img width="556" alt="Bildschirmfoto 2021-04-10 um 20 21 41" src="https://user-images.githubusercontent.com/17240275/114280832-76188b00-9a3b-11eb-81b9-a2f6e8214c5a.png">

**Comment by obany** [comment] 2021-04-12 11:05
I have been unable to reproduce this, is it reproducible on your setup ? Could you DM me the wallet backup.

**Comment by r-c-k** [comment] 2021-04-12 11:37
Yes it is reproducible using the same stronghold with 9 accounts. 
It is however not reproducible with a newly created stronghold with only 1 account.

Will dm you the file.

**Comment by cvarley100** [comment] 2021-04-12 19:38
Should be fixed in 0.4.0 latest.

**Closed by cvarley100** 2021-04-12 19:38 UTC
Labels: bug
