### ISSUE TITLE
DOES NOT END THE PROCESS

### ISSUE THREAD

**Issue by Marcssann** [iotaledger/firefly#1009] opened 2021-04-22 17:21 UTC
Good afternoon!
After the program recognizes my .kdbx backup, and reports that it has been successfully restored, I click on continue but it goes to a blank screen and the process hangs.

Firefly v1.0.0
Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64
CPU count: 4
Total Memory: 7973.4 MB
Free Memory: 1649.3 MB

**Comment by MiKeF05** [comment] 2021-04-22 17:43
Did you try to set the language to English? I think there is a bug with the languages which will be fixed with the next release.

**Comment by Marcssann** [comment] 2021-04-22 19:25
I changed the language to English and it worked, thanks

**Comment by MiKeF05** [comment] 2021-04-26 19:00
@Marcssann Would be good to close this issue. Thank you

**Comment by rajivshah3** [comment] 2021-04-26 20:38
Closing as duplicate of #1005

**Closed by rajivshah3** 2021-04-26 20:38 UTC
Labels: bug
