### ISSUE TITLE
Usability: Pin input without "Continue" button

### ISSUE THREAD

**Issue by dev0pa** [iotaledger/firefly#735] opened 2021-03-25 11:23 UTC
After correct pin input, automatically forward.

**Comment by rafaeldjpbrochado** [comment] 2021-03-25 11:49
Duplicate of https://github.com/iotaledger/firefly/issues/332, feel free to close this issue.

**Comment by obany** [comment] 2021-03-25 15:18
https://github.com/iotaledger/firefly/issues/332

**Closed by obany** 2021-03-25 15:18 UTC
