### ISSUE TITLE
JavaScript error OS X Catalina

### ISSUE THREAD

**Issue by pxdg2** [iotaledger/firefly#1016] opened 2021-04-23 13:56 UTC
## Issue description
Getting the error message below, followed by a blank screen

## Wallet version
1.0.0

## System specification
OS X Catalina 10.15.7

## Is it a repeatable issue?
Yes, happens every time, also on older systems.
Beta version was working fine.

## Steps To reproduce the issue
Open Firefly

## Expected behaviour
No error

## Errors

![Bildschirmfoto 2021-04-23 um 15 39 06](https://user-images.githubusercontent.com/83077755/115881365-f54e8b80-a44b-11eb-8f83-1b4b65e5d90d.png)

**Comment by rajivshah3** [comment] 2021-04-26 21:03
Closing as duplicate of #1006

**Closed by rajivshah3** 2021-04-26 21:03 UTC
Labels: bug
