### ISSUE TITLE
Sending funds from Firefly to Binance (error)

### ISSUE THREAD

**Issue by Mightyhoof** [iotaledger/firefly#1146] opened 2021-05-11 07:14 UTC
## Wallet version

Which version of wallet are you using?

- 1.1.0

## System specification

What is your operating system?

Win10

## Is it a repeatable issue?

Y

**Comment by MiKeF05** [comment] 2021-05-11 09:18
Binance is right now integrating all things so withdrawals are not yet available. Have a look at the news from Binance when the implemenation is done.

**Comment by rajivshah3** [comment] 2021-05-12 01:04
Duplicate of #1119

**Closed** 2021-05-12 01:03 UTC
Labels: bug
