### ISSUE TITLE
Unfortunately an error has occurred in Firefly.

### ISSUE THREAD

**Issue by learner2019** [iotaledger/firefly#1619] opened 2021-10-31 17:41 UTC
### Issue description

help me please!

App Version: 1.2.0

platform: win32
platformVersion: 10.0.18363
platformArchitecture: x64
cpuCount: 8
totalMem: 16304.8 MB
freeMem: 11362.1 MB
userPath: C:\Users\Amir_Mobin\AppData\Roaming\Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_CONNECTION_TIMED_OUT

### Firefly version

1.2.0

### OS details

windows 10 Enterprise ver 1909

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. I don't know
2.
3.
...

### Expected behaviour

I don't know

### Actual behaviour

I don't know

### Errors

App Version: 1.2.0

platform: win32
platformVersion: 10.0.18363
platformArchitecture: x64
cpuCount: 8
totalMem: 16304.8 MB
freeMem: 11362.1 MB
userPath: C:\Users\Amir_Mobin\AppData\Roaming\Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_CONNECTION_TIMED_OUT

**Comment by MiKeF05** [comment] 2021-12-24 12:03
@learner2019 It seems like you can´t connect to the node. Do you use a work PC, VPN or a special firewall?

**Comment by MiKeF05** [comment] 2022-01-05 23:39
@learner2019 Were you able to use Firefly normally after the error appeared?

**Comment by Tuditi** [comment] 2022-08-02 15:13
I'm closing this down, since the issue is outdated. If it is still present in the current Firefly version (1.6.5), please reopen it!

**Closed by Tuditi** 2022-08-02 15:13 UTC
Labels: bug report
