### ISSUE TITLE
Firefly Setup stuck at pin

### ISSUE THREAD

**Issue by anistark** [iotaledger/firefly#1287] opened 2021-07-22 08:27 UTC
## Issue description

Setting Firefly for first time. Imported old seed, set password then gave pin. Confirmed pin.
Stuck in this state. Clicking the button does nothing. No error logs too.

## Wallet version

v1.1.0

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

Linux. Manjaro Linux. Arch Linux distro.

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Downloaded Firefly.
2. During Setup, Stuck on Verify Pin code screen

## Expected behaviour

I imagine it should take me to the next page or dashboard.

## Actual behaviour

Stuck on this screen. It's not frozen. Just clicking on Confirm PIN code button does nothing.

## Errors

No Errors in logs

**Comment by hristo-mavrodiev** [comment] 2021-07-31 13:18
You can try to delete your ` ~/.config/Firefly` directory

**Comment by mrM71** [comment] 2021-08-05 20:51
Deleting the config folder doesn't help. While running it via cmd, i'm getting below error:
Error occurred in handler for 'keychain-set': [Error: The name org.freedesktop.secrets was not provided by any .service files]

**Comment by hristo-mavrodiev** [comment] 2021-08-06 05:02
Then stop Firefly, uninstall it, delete config folder, install it again - the newest version.

**Comment by Aulak** [comment] 2021-08-06 14:44
I had the same issue on my Endeavour Kde(Arch) install. I fixed it on both my computers by installing Gnome-Keyring

**Comment by mrM71** [comment] 2021-08-06 18:08
> Then stop Firefly, uninstall it, delete config folder, install it again - the newest version.

I'm using latest version & as i wrote before, deleting of the config folder doesn't help. Linux is using app image, so nothing to install/uninstall but thanks...

**Comment by mrM71** [comment] 2021-08-06 18:13
> I had the same issue on my Endeavour Kde(Arch) install. I fixed it on both my computers by installing Gnome-Keyring

That one helped, thanks mate.

**Comment by ekofluid-it** [comment] 2021-08-10 12:39
Is duplicate of https://github.com/iotaledger/firefly/issues/1149

**Comment by krdh** [comment] 2021-08-28 21:16
Kinda found this bug when I switched from Manjaro-Gnome to Manjaro-KDE-plasma.
If you want a quick fix you can use KeePassXC, it has a 'Freedesktop.org Secret Service integration' similar to gnome-keyring and *-keyring
It works, got firefly running.
Firefly is not the only .appimage with this problem,  had same problem with zap wallet .appimage.

[Secret Service API Draft](https://specifications.freedesktop.org/secret-service/latest/)

**Comment by Dimfred** [comment] 2021-11-20 11:22
Same problem here. It is weird that firefly can't access the keyring. In VSCode the gnome-keyring is also a dependency and there I don't have any issues. Would be great to have a definitive fix for that.

**Comment by rajivshah3** [comment] 2021-11-21 20:49
Hi, does installing `libsecret-1-dev` (Ubuntu) or `libsecret` (Arch Linux) resolve the issue?

**Comment by ekofluid-it** [comment] 2021-11-22 07:34
> Hi, does installing `libsecret-1-dev` (Ubuntu) or `libsecret` (Arch Linux) resolve the issue?

No, it requires *-keyring.

**Comment by z0rti** [comment] 2021-11-28 16:42
Installed these on ubuntu 20.04:
libsecret-1-0 libsecret-1-0 gnome-keyring gnome-keyring-pkcs11 libgnome-keyring-common libpam-gnome-keyring python3-keyring ubuntu-keyring
Still get the error "Unknown or unsupported transport “disabled” for address “disabled:”"

**Comment by nicole-obrien** [comment] 2022-01-06 01:36
Duplicate of #1149

**Closed by nicole-obrien** 2022-01-06 01:36 UTC
Labels: type:bug, status:duplicate, platform:linux
