### ISSUE TITLE
Removed accounts, reappear after refresh

### ISSUE THREAD

**Issue by dev0pa** [iotaledger/firefly#738] opened 2021-03-25 11:55 UTC
Removed accounts, reappear after refresh

Firefly v0.3.1
Platform: win10 64

**Comment by obany** [comment] 2021-03-25 17:34
Can you provide more details on the steps to reproduce this?

**Comment by baylander** [comment] 2021-03-25 17:50
Can confirm the above mentioned behavior.

Problem: Account will reappear after deletion,

Handling:
1) Two accounts available (see "1.jpg)
1) Delete "Account 2" (see "2.jpg")
-> "Account 2" is gone (see "3.jpg)
2) Refresh Transcations
-> "Account 2"will appear again (see "4.jpg")

![1](https://user-images.githubusercontent.com/29330260/112519676-e320f500-8d9a-11eb-8943-07a8eecca7de.JPG)
![2](https://user-images.githubusercontent.com/29330260/112519687-e5834f00-8d9a-11eb-8179-1f946d385167.JPG)
![3](https://user-images.githubusercontent.com/29330260/112519708-e9af6c80-8d9a-11eb-8f8f-af39f5775ea9.JPG)
![4](https://user-images.githubusercontent.com/29330260/112519714-eb793000-8d9a-11eb-82fb-d7cb78111f5c.JPG)

**Comment by dev0pa** [comment] 2021-03-25 22:43
exactly the same for me

**Comment by obany** [comment] 2021-03-26 10:28
We have now identified the cause of this and will put a fix in place

**Comment by obany** [comment] 2021-03-26 12:13
Also a dupe of https://github.com/iotaledger/firefly/issues/674 so will close this one for now

**Closed by obany** 2021-03-26 12:13 UTC
Labels: bug
