### ISSUE TITLE
Firefly Send nonresposive if non-numeric character entered first

### ISSUE THREAD

**Issue by cfantarella** [iotaledger/firefly#1638] opened 2021-11-20 03:35 UTC
### Issue description

If you enter an amount starting with decimal point (ie. not a digit) then app becomes unresponsive to any further input. 
If you enter a value starting with any number (eg. 0.1 or 100.1) you're OK, but if you enter something like .1 then app gets stuck.

### Firefly version

v1.2.0

### OS details

Windows 10 Home 19043.1348

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Click "Send"
2. Enter address
3. Enter ".1" for the amount
...

### Expected behaviour

The amount in dollars to show, just like when entering a value like 5.1

### Actual behaviour

Firefly becomes unresponsive and program needs to be closed

**Comment by maxwellmattryan** [comment] 2021-11-20 10:18
Hey @cfantarella, thanks for the report. This is a duplicate of #1168, which although whose fix is not released in production yet, has been merged into the `develop` branch. Hopefully this will get out soon 👍

**Closed by maxwellmattryan** 2021-11-20 10:18 UTC
Labels: type:bug, status:duplicate
