### ISSUE TITLE
[Bug report]: (preload context) error

### ISSUE THREAD

**Issue by merijncampo** [iotaledger/firefly#7357] opened 2023-08-24 20:03 UTC
### Platform

Desktop

### Version

1.7.3

### Description

After update from 1.7.2 to 1.7.3 on my MacBook.

It crash at the beginning (with screen). Before it has run the wallet without issues.

### Expected behaviour

Normally open the firefly wallet

### Actual behaviour

Error

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

White screen

### Error Messages

App Version: 1.7.3

platform: macOS
platformVersion: 11.7.9
platformArchitecture: x64
cpuCount: 4
totalMem: 4096.0 MB
freeMem: 85.3 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
 Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
 Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment] 2023-08-25 07:32
Duplicate of https://github.com/iotaledger/firefly/issues/7324
A new version with the fix will be released soon 🙏🏼

**Closed by begonaalvarezd** 2023-08-25 07:32 UTC
Labels: bug report
