### ISSUE TITLE
[Feature request]: Display the live count of votes to reach quorum in Governance

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#7643] opened 2023-10-23 01:11 UTC
### Task description

Implement fields in the overview of a governance proposal that display:
- the number of votes that determine the quorum at the current milestone during counting
- the number of total votes that have currently been counted

Display both as a number and percentage value of the circulating supply.

Highlight if the proposal has reached the quorum (green color percentage) or is below the quorum (red color percentage)

### Requirements

**For IOTA Firefly:**

To calculate the votes that determine the quorum:

**Calculate the maximum possible votes at a milestone:**
   - (number of milestones passed) * (circulating supply in micros/1000) 
      - circulating supply is taken from the API endpoint: https://api.stardust-mainnet.iotaledger.net/api/supply/v1/circulating, which is configured in IOTA, so it needs to be calculated * 1.000.000
   take the result and calculate 5% of it (our current quorum) 
   
To calculate the live count of votes, combine the counted votes for all options of a proposal, including "Abstain."

**For Shimmer Firefly:**

To calculate the votes that determine the quorum:

**Calculate the maximum possible votes at a milestone:**
   - (number of milestones passed) * (1,813,620,509,061,360/1000) 
      take the result and calculate 5% of it (our current quorum) 

To calculate the live count of votes, combine the counted votes for all options of a proposal, including "Abstain."

As we may want to change the quorum in the future, we could think about how to update the quorum percentage without creating a new Firefly release. It could also be helpful to create an endpoint for this.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by Dr-Electron** [comment] 2023-10-23 02:25
Duplicate of https://github.com/iotaledger/firefly/issues/7644

**Closed** 2023-10-23 05:19 UTC
