### ISSUE TITLE
Portfolio chart goes negative and starts from the wrong date

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#864] opened 2021-04-12 19:35 UTC
## Issue description

Sometimes the portfolio chart displays the wrong balance and goes negative. Other times it starts from the wrong date (i.e before I first received funds)

## Wallet version

0.4.0

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Exact steps are not clear. Send and receive various transactions across accounts internal and external. Root cause is likely missing messages.

**Comment by Tuditi** [comment] 2022-08-02 15:06
I'm closing this down, since the issue is outdated. If it is still present in the current Firefly version (1.6.5), please reopen it!

**Closed by Tuditi** 2022-08-02 15:06 UTC
Labels: bug report
