### ISSUE TITLE
Wallet PIN Issue

### ISSUE THREAD

**Issue by westbounce** [iotaledger/firefly#2019] opened 2022-01-05 08:09 UTC
### Issue description

Cannot log into my firely wallet profile anymore because the wallet says that the PIN is incorrect. However I am 100% sure that the PIN is in fact correct. Seriously no doubt about that. I had set up the wallet in version 1.3.0 and have now updated to 1.3.2, but the issue still persists. PLEASE can you fix this asap. 

### Firefly version

1.3.2

### OS details

1909 build 18363.1977

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. start firely
2. select profile
3. enter pin
...

### Expected behaviour

profile can be accessed with pin

### Actual behaviour

profiel cannot be access with pin

### Errors

x incorrect attempts

**Comment by MiKeF05** [comment] 2022-01-05 10:49
Can you try to create a new profile and restore it either with your 24 words or your stronghold backup? If you use a ledger device then restore it with your ledger.

**Comment by MiKeF05** [comment] 2022-01-05 10:53
Can you go to the credential manager in windows and paste a screenshot of how many credentials you have for Firefly? How many profiles do you have in Firefly? It should look like this


![image](https://user-images.githubusercontent.com/71659397/148206223-41316eeb-b591-4645-96d3-e83216020077.png)

**Comment by westbounce** [comment] 2022-01-05 13:21
Actually there are zero credentials for Firefly in windows credential manager. Not sure if there were any beforehand.

**Comment by MiKeF05** [comment] 2022-01-05 21:08
This is strange. Something deletes the credentials from the windows credentials manager. Therefore the PIN can´t be seen by Firefly.

**Comment by rajivshah3** [comment] 2022-01-05 21:18
Hi @westbounce , are you able to update Windows? Microsoft fixed an issue last year that seems somewhat related to this.

References:

https://answers.microsoft.com/en-us/windows/forum/all/systemwide-password-amnesia-v2004-build-19041173/232381f8-e2c6-4e8a-b01c-712fceb0e39e
https://www.zdnet.com/article/windows-10-password-problems-microsoft-says-its-fixing-bad-password-amnesia-bug/

**Comment by westbounce** [comment] 2022-01-05 21:42
I am afraid I cannot update windows as firefly has been installed on a corporate device

**Comment by nicole-obrien** [comment] 2022-01-06 15:44
Duplicate of #1683

**Closed by nicole-obrien** 2022-01-06 15:44 UTC
Labels: type:bug, status:duplicate
