### ISSUE TITLE
error has occurred in firefly 

### ISSUE THREAD

**Issue by Sha13332** [iotaledger/firefly#1213] opened 2021-06-20 12:08 UTC
## Issue description

Briefly describe the issue.
the balance is zero 
the network status is disconnected 
## Wallet version
1.1.0

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)
Mac

## Errors

App Version: 1.1.0

platform: macOS
platformVersion: 10.15
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 254.0 MB
userPath: /Users/shahadalhelayl/Library/Application Support/Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at /Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:165586
    at /Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (/Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197594)
    at /Applications/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:191379

**Comment by Sha13332** [comment] 2021-06-20 12:11
sorry, I'm new to github 
if the issue is not clear let me know

**Comment by nicole-obrien** [comment] 2022-01-06 15:35
Duplicate of #1087

**Closed by nicole-obrien** 2022-01-06 15:35 UTC
Labels: type:bug, status:duplicate
