### ISSUE TITLE
[Bug report]: Cannot read property 'selectSeed' of undefined

### ISSUE THREAD

**Issue by opatz-consulting** [iotaledger/firefly#2915] opened 2022-04-14 22:14 UTC
### Platform

Desktop

### Version

1.4.2

### Description

Cannot read property 'selectSeed' of undefined

**Callback Error getLedgerDeviceStatus on migration from IOTA Legacy to IOTA (Firefly) on Ledger**

I have successfully generated my new address with IOTA App on Ledger.
After that step, I have to switch to the IOTA Legacy App on Ledger.

I got an exception after press the "confirm" button on this screen:
![Bildschirmfoto 2022-04-15 um 00 12 15](https://user-images.githubusercontent.com/68771385/163484715-4074381c-a81f-487b-9984-46b5cf75ee19.png)

<img width="813" alt="Bildschirmfoto 2022-04-15 um 00 13 13" src="https://user-images.githubusercontent.com/68771385/163484774-8d181b9c-bfef-4093-8009-aac4ec0051d1.png">

### Expected behaviour

I could press the confirm button successfully while IOTA legacy app was opened and continue migration from Legacy to Firefly.

### Actual behaviour

<img width="813" alt="Bildschirmfoto 2022-04-15 um 00 13 13" src="https://user-images.githubusercontent.com/68771385/163484784-883ff20a-c2b2-4852-bcb7-fe96f70a7252.png">

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

![Bildschirmfoto 2022-04-15 um 00 06 28](https://user-images.githubusercontent.com/68771385/163484009-1017810b-cf53-4019-a826-544d99bbb3ea.png)

Press the "confirm button"
![Bildschirmfoto 2022-04-15 um 00 12 15](https://user-images.githubusercontent.com/68771385/163484660-e0c909b3-4654-47a8-b4c1-cef7d4004ebc.png)

### Operating System

Mac

### Diagnostics

```shell
App Version: 1.4.2

platform: macOS
platformVersion: 12.3.1
platformArchitecture: x64
cpuCount: 12
totalMem: 16384.0 MB
freeMem: 269.5 MB

Error Type: Callback Error getLedgerDeviceStatus

TypeError: Cannot read property 'selectSeed' of undefined
    at o (file:///Applications/Crypto/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2882882)
    at s (file:///Applications/Crypto/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2232324)
    at onSuccess (file:///Applications/Crypto/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2232138)
    at e.<computed>.<computed> (file:///Applications/Crypto/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2204288)
    at Function.<anonymous> (file:///Applications/Crypto/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2197511)
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Crash Status

Non-responsive

### Error Messages

Cannot read property 'selectSeed' of undefined

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment] 2022-04-14 22:36
Duplicate of https://github.com/iotaledger/firefly/issues/2783. This issue is fixed in the next release.

**Closed by rajivshah3** 2022-04-14 22:36 UTC
Labels: bug report
