### ISSUE TITLE
[Task]: Fix invalid coin type for existing profiles

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7438] opened 2023-09-18 15:24 UTC
### Task description

Reported on Firefly Shimmer 2.1.7-beta-1
Using the latest beta, users are getting coin type errors on existing profiles. We need to make sure this does not happen in existing shimmer profiles (shimmer is important, testnet not as much) coming from previous firefly shimmer versions
![image](https://github.com/iotaledger/firefly/assets/3624944/278f555a-c433-4d83-b899-2f6d93479db9)

Please note the message given to the testers, this might not be a bug, we just need to make sure its not and fix it if it is:
> if it happened with an old profile, not all beta profiles are compatible across beta versions, because they are testing versions. If you want to test the beta, i recommend cleaning up your old profiles and creating new ones. We will test your error to make sure it doesnt happen in production

https://discord.com/channels/397872799483428865/1148183829866106880/1152316672443678761

### Requirements

Fix invalid coin type for existing profiles, if necessary

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by msarcev** [comment] 2023-09-21 10:27
Closing as couldn't reproduce on Shimmer network.

**Closed by msarcev** 2023-09-21 10:27 UTC
Labels: type:fix
