### ISSUE TITLE
gpu_data_manager_impl_private.cc(445)] GPU process isn't usable.

### ISSUE THREAD

**Issue by Niieene** [iotaledger/firefly#1853] opened 2021-12-22 12:55 UTC
### Issue description

Hello,
on fedora 35 with native NVidia driver 470.94 i get this error when i start firefly app image.
On my laptop, which has the same fedora version, but no NVidia or AMD card, firefly works.
Discord has the same error.

workaround: start firefly with --nosandbox or better --disable-gpu-sandbox

### Firefly version

1.3.0

### OS details

Fedora 35 64bit Nvidia 470.97

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...
start simply the app

### Expected behaviour

app starts

### Actual behaviour

app stops to start with:
3:46:31.674 › Checking for update
13:46:31.807 › Update for version 1.3.0 is not available (latest version: 1.3.0, downgrade is disallowed).
(node:13054) Electron: Loading non-context-aware native module in renderer: '/tmp/.org.chromium.Chromium.Pj7JhX'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[12985:1222/134631.990818:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

### Errors

3:46:31.674 › Checking for update
13:46:31.807 › Update for version 1.3.0 is not available (latest version: 1.3.0, downgrade is disallowed).
(node:13054) Electron: Loading non-context-aware native module in renderer: '/tmp/.org.chromium.Chromium.Pj7JhX'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[12985:1222/134631.990818:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

**Comment by rajivshah3** [comment] 2021-12-28 18:58
Duplicate of #1628

**Closed by rajivshah3** 2021-12-28 18:58 UTC
Labels: type:bug
